                        var uppifter = { "INK2R-2013": [
                                {"id": 7011, "namn": "Räkenskapsår Fr.o.m",  "typ": "Datum_A"}, 
                                {"id": 7012, "namn": "Räkenskapsår T.o.m",  "typ": "Datum_A"}, 

                                {"id": 7201, "namn": "2.1", "typ": "Numeriskt_A"}, 
                                {"id": 7202, "namn": "2.2", "typ": "Numeriskt_A"}, 
                                
                                {"id": 7214, "namn": "2.3", "typ": "Numeriskt_A"}, 
                                {"id": 7215, "namn": "2.4", "typ": "Numeriskt_A"}, 
                                {"id": 7216, "namn": "2.5", "typ": "Numeriskt_A"}, 
                                {"id": 7217, "namn": "2.6", "typ": "Numeriskt_A"},

                                {"id": 7230, "namn": "2.7", "typ": "Numeriskt_A"},
                                {"id": 7231, "namn": "2.8", "typ": "Numeriskt_A"},
                                {"id": 7232, "namn": "2.9", "typ": "Numeriskt_A"},
                                {"id": 7233, "namn": "2.10", "typ": "Numeriskt_A"},
                                {"id": 7234, "namn": "2.11", "typ": "Numeriskt_A"},
                                {"id": 7235, "namn": "2.12", "typ": "Numeriskt_A"},
                                
                                {"id": 7241, "namn": "2.13", "typ": "Numeriskt_A"},
                                {"id": 7242, "namn": "2.14", "typ": "Numeriskt_A"},
                                {"id": 7243, "namn": "2.15", "typ": "Numeriskt_A"},
                                {"id": 7244, "namn": "2.16", "typ": "Numeriskt_A"},
                                {"id": 7245, "namn": "2.17", "typ": "Numeriskt_A"},
                                {"id": 7246, "namn": "2.18", "typ": "Numeriskt_A"},
                                
                                {"id": 7251, "namn": "2.19", "typ": "Numeriskt_A"},
                                {"id": 7252, "namn": "2.20", "typ": "Numeriskt_A"},
                                
                                {"id": 7261, "namn": "2.21", "typ": "Numeriskt_A"},
                                {"id": 7262, "namn": "2.22", "typ": "Numeriskt_A"},
                                {"id": 7263, "namn": "2.23", "typ": "Numeriskt_A"},
                                
                                {"id": 7270, "namn": "2.24", "typ": "Numeriskt_A"},
                                {"id": 7271, "namn": "2.25", "typ": "Numeriskt_A"},
                                
                                {"id": 7281, "namn": "2.26", "typ": "Numeriskt_A"},

                                {"id": 7301, "namn": "2.27", "typ": "Numeriskt_A"},
                                {"id": 7302, "namn": "2.28", "typ": "Numeriskt_A"},
                                
                                {"id": 7321, "namn": "2.29", "typ": "Numeriskt_A"},
                                {"id": 7322, "namn": "2.30", "typ": "Numeriskt_A"},
                                {"id": 7323, "namn": "2.31", "typ": "Numeriskt_A"},
                                
                                {"id": 7331, "namn": "2.32", "typ": "Numeriskt_A"},
                                {"id": 7332, "namn": "2.33", "typ": "Numeriskt_A"},
                                {"id": 7333, "namn": "2.34", "typ": "Numeriskt_A"},
                                
                                {"id": 7350, "namn": "2.35", "typ": "Numeriskt_A"},
                                {"id": 7351, "namn": "2.36", "typ": "Numeriskt_A"},
                                {"id": 7352, "namn": "2.37", "typ": "Numeriskt_A"},
                                {"id": 7353, "namn": "2.38", "typ": "Numeriskt_A"},
                                {"id": 7354, "namn": "2.39", "typ": "Numeriskt_A"},
                                
                                {"id": 7360, "namn": "2.40", "typ": "Numeriskt_A"},
                                {"id": 7361, "namn": "2.41", "typ": "Numeriskt_A"},
                                {"id": 7362, "namn": "2.42", "typ": "Numeriskt_A"},
                                {"id": 7363, "namn": "2.43", "typ": "Numeriskt_A"},
                                {"id": 7364, "namn": "2.44", "typ": "Numeriskt_A"},
                                {"id": 7365, "namn": "2.45", "typ": "Numeriskt_A"},
                                {"id": 7366, "namn": "2.46", "typ": "Numeriskt_A"},
                                {"id": 7367, "namn": "2.47", "typ": "Numeriskt_A"},
                                {"id": 7368, "namn": "2.48", "typ": "Numeriskt_A"},
                                {"id": 7369, "namn": "2.49", "typ": "Numeriskt_A"},
                                {"id": 7370, "namn": "2.50", "typ": "Numeriskt_A"},
                                
                                {"id": 7410, "namn": "3.1", "typ": "Numeriskt_A"},
                                
                                {"id": 7411, "namn": "3.2+", "typ": "Numeriskt_A"},
                                {"id": 7510, "namn": "3.2-", "typ": "Numeriskt_A"},
                                
                                {"id": 7412, "namn": "3.3", "typ": "Numeriskt_A"},
                                {"id": 7413, "namn": "3.4", "typ": "Numeriskt_A"},
                                {"id": 7511, "namn": "3.5", "typ": "Numeriskt_A"},
                                {"id": 7512, "namn": "3.6", "typ": "Numeriskt_A"},
                                {"id": 7513, "namn": "3.7", "typ": "Numeriskt_A"},
                                {"id": 7514, "namn": "3.8", "typ": "Numeriskt_A"},
                                {"id": 7515, "namn": "3.9", "typ": "Numeriskt_A"},
                                {"id": 7516, "namn": "3.10", "typ": "Numeriskt_A"},
                                {"id": 7517, "namn": "3.11", "typ": "Numeriskt_A"},
                                
                                {"id": 7414, "namn": "3.12+", "typ": "Numeriskt_A"},
                                {"id": 7518, "namn": "3.12-", "typ": "Numeriskt_A"},
                                
                                {"id": 7415, "namn": "3.13+", "typ": "Numeriskt_A"},
                                {"id": 7519, "namn": "3.13-", "typ": "Numeriskt_A"},
                                
                                {"id": 7416, "namn": "3.14+", "typ": "Numeriskt_A"},
                                {"id": 7520, "namn": "3.14-", "typ": "Numeriskt_A"},

                                {"id": 7417, "namn": "3.15", "typ": "Numeriskt_A"},
                                {"id": 7521, "namn": "3.16", "typ": "Numeriskt_A"},
                                {"id": 7522, "namn": "3.17", "typ": "Numeriskt_A"},
                                {"id": 7418, "namn": "3.18", "typ": "Numeriskt_A"},
                                {"id": 7523, "namn": "3.19", "typ": "Numeriskt_A"},
                                {"id": 7524, "namn": "3.20", "typ": "Numeriskt_A"},
                                {"id": 7419, "namn": "3.21", "typ": "Numeriskt_A"},
                                {"id": 7420, "namn": "3.22", "typ": "Numeriskt_B"},
                                {"id": 7525, "namn": "3.23", "typ": "Numeriskt_B"},
                                
                                {"id": 7421, "namn": "3.24+", "typ": "Numeriskt_A"},
                                {"id": 7526, "namn": "3.24-", "typ": "Numeriskt_A"},

                                {"id": 7422, "namn": "3.25+", "typ": "Numeriskt_A"},
                                {"id": 7527, "namn": "3.25-", "typ": "Numeriskt_A"},
                                
                                {"id": 7528, "namn": "3.26", "typ": "Numeriskt_A"},
                                {"id": 7450, "namn": "3.27=+", "typ": "Numeriskt_B"},
                                {"id": 7550, "namn": "3.28=-", "typ": "Numeriskt_B"}],
                                
                                "INK2S-2013": [
                                {"id": 7011, "namn": "Räkenskapsår Fr.o.m",  "typ": "Datum_A"}, 
                                {"id": 7012, "namn": "Räkenskapsår T.o.m",  "typ": "Datum_A"}, 

                                {"id": 7650, "namn": "4.1", "typ": "Numeriskt_B"},
                                {"id": 7750, "namn": "4.2", "typ": "Numeriskt_B"},
                                
                                {"id": 7651, "namn": "4.3a", "typ": "Numeriskt_A"},
                                {"id": 7652, "namn": "4.3b", "typ": "Numeriskt_A"},
                                {"id": 7653, "namn": "4.3c", "typ": "Numeriskt_A"},
                                
                                {"id": 7751, "namn": "4.4a", "typ": "Numeriskt_A"},
                                {"id": 7764, "namn": "4.4b", "typ": "Numeriskt_A"},
                                
                                {"id": 7752, "namn": "4.5a", "typ": "Numeriskt_A"},
                                {"id": 7753, "namn": "4.5b", "typ": "Numeriskt_A"},
                                {"id": 7754, "namn": "4.5c", "typ": "Numeriskt_A"},
                                
                                {"id": 7654, "namn": "4.6a", "typ": "Numeriskt_A"},
                                {"id": 7668, "namn": "4.6b", "typ": "Numeriskt_A"},
                                {"id": 7655, "namn": "4.6c", "typ": "Numeriskt_A"},
                                {"id": 7667, "namn": "4.6d", "typ": "Numeriskt_A"},
                                {"id": 7665, "namn": "4.6e", "typ": "Numeriskt_A"},
                                
                                {"id": 7755, "namn": "4.7a", "typ": "Numeriskt_B"},
                                {"id": 7656, "namn": "4.7b", "typ": "Numeriskt_B"},
                                {"id": 7756, "namn": "4.7c", "typ": "Numeriskt_B"},
                                {"id": 7657, "namn": "4.7d", "typ": "Numeriskt_B"},
                                {"id": 7658, "namn": "4.7e", "typ": "Numeriskt_B"},
                                {"id": 7757, "namn": "4.7f", "typ": "Numeriskt_B"},
                                
                                {"id": 7758, "namn": "4.8a", "typ": "Numeriskt_B"},
                                {"id": 7659, "namn": "4.8b", "typ": "Numeriskt_B"},
                                {"id": 7660, "namn": "4.8c", "typ": "Numeriskt_B"},
                                {"id": 7759, "namn": "4.8d", "typ": "Numeriskt_B"},

                                {"id": 7666, "namn": "4.9+", "typ": "Numeriskt_B"},
                                {"id": 7765, "namn": "4.9-", "typ": "Numeriskt_B"},

                                {"id": 7661, "namn": "4.10+", "typ": "Numeriskt_B"},
                                {"id": 7760, "namn": "4.10-", "typ": "Numeriskt_B"},
                                
                                {"id": 7761, "namn": "4.11", "typ": "Numeriskt_A"},
                                {"id": 7662, "namn": "4.12", "typ": "Numeriskt_A"},
                                
                                {"id": 7663, "namn": "4.13+", "typ": "Numeriskt_B"},
                                {"id": 7762, "namn": "4.13-", "typ": "Numeriskt_B"},
                                
                                {"id": 7763, "namn": "4.14a", "typ": "Numeriskt_A"},
                                {"id": 7664, "namn": "4.14b", "typ": "Numeriskt_A"},
                                
                                {"id": 7670, "namn": "4.15=+", "typ": "Numeriskt_B"},
                                {"id": 7770, "namn": "4.16=-", "typ": "Numeriskt_B"},
                                
                                {"id": 8020, "namn": "4.17", "typ": "Numeriskt_A"},
                                {"id": 8021, "namn": "4.18", "typ": "Numeriskt_A"},
                                {"id": 8023, "namn": "4.19", "typ": "Numeriskt_B"},
                                {"id": 8026, "namn": "4.20", "typ": "Numeriskt_B"},
                                {"id": 8022, "namn": "4.21", "typ": "Numeriskt_A"},
                                
                                {"id": 8040, "namn": "Redovisningskonsult JA", "typ": "Str_X"},
                                {"id": 8041, "namn": "Redovisningskonsult NEJ", "typ": "Str_X"},

                                {"id": 8044, "namn": "Revision JA", "typ": "Str_X"},
				{"id": 8045, "namn": "Revision NEJ", "typ": "Str_X"}],

"INK3K-2013": [
{"namn": "Räkenskapsårets början", "id": "7011", "typ": "Datum_D"},
{"namn": "Räkenskapsårets slut", "id": "7012", "typ": "Datum_D"},
{"namn": "2.1 Resultat från handelsbolagsandel enligt blankett N3B Överskott", "id": "8602", "typ": "Numeriskt_B"},
{"namn": "2.1 Resultat från handelsbolagsandel enligt blankett N3B Underskott", "id": "8703", "typ": "Numeriskt_B"},
{"namn": "2.2 Intäktsränta, utdelning eller andra kapitalintäkter", "id": "8600", "typ": "Numeriskt_A"},
{"namn": "2.3 Kapitalvinst m.m.", "id": "8601", "typ": "Numeriskt_A"},
{"namn": "2.4 Skuldränta m.m.", "id": "8700", "typ": "Numeriskt_A"},
{"namn": "2.5 Kostnad för kapitalförvaltning", "id": "8701", "typ": "Numeriskt_A"},
{"namn": "2.6 Kapitalförlust m.m.", "id": "8702", "typ": "Numeriskt_A"},
{"namn": "2.7 Lämnade koncernbidrag och uppskov med kapitalvinst enligt N4", "id": "8704", "typ": "Numeriskt_B"},
{"namn": "2.8 Erhållna koncernbidrag och återfört uppskov av kapitalvinst enligt N4", "id": "8603", "typ": "Numeriskt_B"},
{"namn": "2.9 Outnyttjat underskott från föregående år", "id": "8705", "typ": "Numeriskt_B"},
{"namn": "2.10 Beräknad schablonintäkt på fondandelar ägda vid ingången av kalenderåret", "id": "8607", "typ": "Numeriskt_B"},
{"namn": "2.11 Intäkt negativ justerad anskaffningsutgift", "id": "8606", "typ": "Numeriskt_B"},
{"namn": "2.12 Återföring av periodiseringsfond", "id": "8604", "typ": "Numeriskt_B"},
{"namn": "2.13 Beräknad schablonintäkt på kvarvarande periodiserings-fonder vid beskattningsårets ingång", "id": "8605", "typ": "Numeriskt_B"},
{"namn": "2.14 Avsättning till periodiseringsfond", "id": "8706", "typ": "Numeriskt_B"},
{"namn": "2.15 Periodiskt understöd i familjestiftelse", "id": "8707", "typ": "Numeriskt_A"},
{"namn": "2.16 Överskott", "id": "8610", "typ": "Numeriskt_B"},
{"namn": "2.17 Underskott", "id": "8710", "typ": "Numeriskt_B"}],

"INK3R-2013": [
{"namn": "Räkenskapsårets början", "id": "7011", "typ": "Datum_D"},
{"namn": "Räkenskapsårets slut", "id": "7012", "typ": "Datum_D"},
{"namn": "5.1 Immateriella anläggningstillgångar", "id": "8720", "typ": "Numeriskt_A"},
{"namn": "5.2 Byggnader och markanläggningar", "id": "8721", "typ": "Numeriskt_A"},
{"namn": "5.3 Mark och andra tillgångar som inte får skrivas av", "id": "8722", "typ": "Numeriskt_A"},
{"namn": "5.4 Maskiner och inventarier", "id": "8723", "typ": "Numeriskt_A"},
{"namn": "5.5 Finansiella anläggningstillgångar","id": "8724", "typ": "Numeriskt_A"},
{"namn": "5.6 Övriga anläggningstillgångar", "id": "8725", "typ": "Numeriskt_A"},
{"namn": "5.7 Varulager", "id": "8726", "typ": "Numeriskt_A"},
{"namn": "5.8 Kundfordringar", "id": "8727", "typ": "Numeriskt_A"},
{"namn": "5.9 Övriga fordringar", "id": "8728", "typ": "Numeriskt_A"},
{"namn": "5.10 Upplupna intäkter och förutbetalda kostnader", "id": "8729", "typ": "Numeriskt_A"},
{"namn": "5.11 Kassa och bank", "id": "8730", "typ": "Numeriskt_A"},
{"namn": "5.12 Eget kapital", "id": "8735", "typ": "Numeriskt_A"},
{"namn": "5.13 Periodiseringsfonder", "id": "8736", "typ": "Numeriskt_A"},
{"namn": "5.14 Övriga obeskattade reserver", "id": "8737", "typ": "Numeriskt_A"},
{"namn": "5.15 Avsättningar för pensioner och liknande förpliktelser", "id": "8738", "typ": "Numeriskt_A"},
{"namn": "5.16 Övriga avsättningar", "id": "8739", "typ": "Numeriskt_A"},
{"namn": "5.17 Låneskulder", "id": "8740", "typ": "Numeriskt_A"},
{"namn": "5.18 Skatteskulder", "id": "8741", "typ": "Numeriskt_A"},
{"namn": "5.19 Leverantörsskulder", "id": "8742", "typ": "Numeriskt_A"},
{"namn": "5.20 Övriga skulder", "id": "8743", "typ": "Numeriskt_A"},
{"namn": "5.21 Upplupna kostnader och förutbetalda intäkter", "id": "8744", "typ": "Numeriskt_A"},
{"namn": "6.1 Medlemsavgifter (enligt redovisningen)", "id": "8650", "typ": "Numeriskt_A"},
{"namn": "6.2 Serviceavgifter (enligt redovisningen)", "id": "8651", "typ": "Numeriskt_A"},
{"namn": "6.2 Serviceavgifter (som ska tas upp/dras av)", "id": "8671", "typ": "Numeriskt_A"},
{"namn": "6.3 Gåvor och bidrag (enligt redovisningen)", "id": "8652", "typ": "Numeriskt_A"},
{"namn": "6.3 Gåvor och bidrag (som ska tas upp/dras av)", "id": "8672", "typ": "Numeriskt_A"},
{"namn": "6.4 Nettoomsättning (enligt redovisningen)", "id": "8653", "typ": "Numeriskt_A"},
{"namn": "6.4 Nettoomsättning (som ska tas upp/dras av)", "id": "8673", "typ": "Numeriskt_A"},
{"namn": "6.5 Övriga intäkter (enligt redovisningen)", "id": "8654", "typ": "Numeriskt_A"},
{"namn": "6.5 Övriga intäkter (som ska tas upp/dras av)", "id": "8674", "typ": "Numeriskt_A"},
{"namn": "6.6 Varor och legoarbeten (enligt redovisningen)", "id": "8750", "typ": "Numeriskt_A"},
{"namn": "6.6 Varor och legoarbeten (som ska tas upp/dras av)", "id": "8770", "typ": "Numeriskt_A"},
{"namn": "6.7 Övriga externa kostnader (enligt redovisningen)", "id": "8751", "typ": "Numeriskt_A"},
{"namn": "6.7 Övriga externa kostnader (som ska tas upp/dras av)", "id": "8771", "typ": "Numeriskt_A"},
{"namn": "6.8 Personalkostnader (enligt redovisningen)", "id": "8752", "typ": "Numeriskt_A"},
{"namn": "6.8 Personalkostnader (som ska tas upp/dras av)", "id": "8772", "typ": "Numeriskt_A"},
{"namn": "6.9 Av- och nedskrivningar (enligt redovisningen)", "id": "8753", "typ": "Numeriskt_A"},
{"namn": "6.9 Av- och nedskrivningar (som ska tas upp/dras av)", "id": "8773", "typ": "Numeriskt_A"},
{"namn": "6.10 Övriga rörelsekostnader (enligt redovisningen)", "id": "8754", "typ": "Numeriskt_A"},
{"namn": "6.10 Övriga rörelsekostnader (som ska tas upp/dras av)", "id": "8774", "typ": "Numeriskt_A"},
{"namn": "6.11 Resultat från andelar i koncern- och intresseföretag + (enligt redovisningen)", "id": "8655", "typ": "Numeriskt_B"},
{"namn": "6.11 Resultat från andelar i koncern- och intresseföretag + (som ska tas upp/dras av)", "id": "8675", "typ": "Numeriskt_B"},
{"namn": "6.11 Resultat från andelar i koncern- och intresseföretag - (enligt redovisningen)", "id": "8755", "typ": "Numeriskt_B"},
{"namn": "6.11 Resultat från andelar i koncern- och intresseföretag - (som ska tas upp/dras av)", "id": "8775", "typ": "Numeriskt_B"},
{"namn": "6.12 Resultat vid avyttring av övriga finansiella anläggningstillgångar + (enligt redovisningen)", "id": "8656", "typ": "Numeriskt_B"},
{"namn": "6.12 Resultat vid avyttring av övriga finansiella anläggningstillgångar + (som ska tas upp/dras av)", "id": "8676", "typ": "Numeriskt_B"},
{"namn": "6.12 Resultat vid avyttring av övriga finansiella anläggningstillgångar - (enligt redovisningen)", "id": "8756", "typ": "Numeriskt_B"},
{"namn": "6.12 Resultat vid avyttring av övriga finansiella anläggningstillgångar - (som ska tas upp/dras av)", "id": "8776", "typ": "Numeriskt_B"},
{"namn": "6.13 Övriga finansiella intäkter t.ex. ränteintäkter och utdelningar (enligt redovisningen)", "id": "8657", "typ": "Numeriskt_B"},
{"namn": "6.13 Övriga finansiella intäkter t.ex. ränteintäkter och utdelningar (som ska tas upp/dras av)", "id": "8677", "typ": "Numeriskt_B"},
{"namn": "6.14 Nedskrivning av finansiella anläggningstillgångar och kortfristiga placeringar (enligt redovisningen)", "id": "8757", "typ": "Numeriskt_B"},
{"namn": "6.14 Nedskrivning av finansiella anläggnings- tillgångar och kortfristiga placeringar (som ska tas upp/dras av)", "id": "8777", "typ": "Numeriskt_B"},
{"namn": "6.15 Räntekostnader och liknande resultatposter (enligt redovisningen)", "id": "8758", "typ": "Numeriskt_A"},
{"namn": "6.15 Räntekostnader och liknande resultatposter (som ska tas upp/dras av)", "id": "8778", "typ": "Numeriskt_A"},
{"namn": "6.16 Extraordinära intäkter (enligt redovisningen)", "id": "8658", "typ": "Numeriskt_B"},
{"namn": "6.16 Extraordinära intäkter (som ska tas upp/dras av)", "id": "8678", "typ": "Numeriskt_B"},
{"namn": "6.17 Extraordinära kostnader (enligt redovisningen)", "id": "8759", "typ": "Numeriskt_B"},
{"namn": "6.17 Extraordinära kostnader (som ska tas upp/dras av)", "id": "8779", "typ": "Numeriskt_B"},
{"namn": "6.18 Återföring av periodiseringsfond + (enligt redovisningen)", "id": "8659", "typ": "Numeriskt_B"},
{"namn": "6.18 Återföring av periodiseringsfond + (som ska tas upp/dras av)", "id": "8679", "typ": "Numeriskt_B"},
{"namn": "6.19 Avsättning till periodiseringsfond - (enligt redovisningen)", "id": "8760", "typ": "Numeriskt_B"},
{"namn": "6.19 Avsättning till periodiseringsfond - (som ska tas upp/dras av)", "id": "8780", "typ": "Numeriskt_B"},
{"namn": "6.20 Övriga bokslutsdispositioner t.ex. lämnade/mottagna koncernbidrag (enligt redovisningen)", "id": "8660", "typ": "Numeriskt_B"},
{"namn": "6.20 Övriga bokslutsdispositioner t.ex. lämnade/mottagna koncernbidrag (som ska tas upp/dras av)", "id": "8680", "typ": "Numeriskt_B"},
{"namn": "6.20 Övriga bokslutsdispositioner t.ex. lämnade/mottagna koncernbidrag (enligt redovisningen)", "id": "8761", "typ": "Numeriskt_B"},
{"namn": "6.20 Övriga bokslutsdispositioner t.ex. lämnade/mottagna koncernbidrag (som ska tas upp/dras av)", "id": "8781", "typ": "Numeriskt_B"},
{"namn": "6.21 Skatt på årets resultat... (enligt redovisningen)", "id": "8762", "typ": "Numeriskt_A"},
{"namn": "6.22 Resultat enligt redovisningen", "id": "8665", "typ": "Numeriskt_A"},
{"namn": "6.23 Justerat resultat, vinst (som ska tas upp/dras av)", "id": "8685", "typ": "Numeriskt_B"},
{"namn": "6.23 Justerat resultat, förlust (som ska tas upp/dras av)", "id": "8785", "typ": "Numeriskt_B"}],

"INK3S-2013": [
{"namn": "7.1 Justerat resultat från föregående sida p.6.23, vinst +", "id": "8686", "typ": "Numeriskt_B"},
{"namn": "7.2 Justerat resultat från föregående sida p. 6.23 , förlust -", "id": "8786", "typ": "Numeriskt_B"},
{"namn": "7.3 Underskott a. Outnyttjat underskott från föregående år -", "id": "8787", "typ": "Numeriskt_A"},
{"namn": "7.3 Underskott b. Reduktion av underskott med hänsyn till exempelvis ackord +", "id": "8687", "typ": "Numeriskt_A"},
{"namn": "7.4 Kostnader som ska dras av men som inte ingår i det redovisade resultatet -", "id": "8788", "typ": "Numeriskt_A"},
{"namn": "7.5a. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet: a. Beräknad schablonintäkt på kvarvarande periodiseringsfonder vid beskattningsårets utgång +", "id": "8688", "typ": "Numeriskt_B"},
{"namn": "b. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet: b. Beräknad schablonintäkt på fondandelar ägda vid ingången av kalenderåret +", "id": "8693", "typ": "Numeriskt_A"},
{"namn": "c. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet: c. Intäkt negativ justerad anskaffningsutgift +", "id": "8692", "typ": "Numeriskt_A"},
{"namn": "d. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet: d. Övriga intäkter +", "id": "8689", "typ": "Numeriskt_A"},
{"namn": "7.6 Skattemässig korrigering av bokfört resultat vid avyttring av fastighet och bostadsrätt: +", "id": "8690", "typ": "Numeriskt_B"},
{"namn": "7.6 Skattemässig korrigering av bokfört resultat vid avyttring av fastighet och bostadsrätt: -", "id": "8789", "typ": "Numeriskt_B"},
{"namn": "7.7 Skogs-/substansminskningsavdrag (specificeras på blankett N8) -", "id": "8790", "typ": "Numeriskt_A"},
{"namn": "7.8 Återföringar vid avyttring av fastighet (t.ex. värdeminskningsavdrag, skogsavdrag) +", "id": "8691", "typ": "Numeriskt_A"},
{"namn": "7.9 Överskott (flyttas till huvudblanketten sid 1, p. 1.1) +", "id": "8695", "typ": "Numeriskt_B"},
{"namn": "7.10 Underskott (flyttas till huvudblanketten sid 1, p. 1.2) -", "id": "8795", "typ": "Numeriskt_B"},
{"namn": "7.11 Vid beskattningsårets utgång ej återförda värdeminskningsavdrag avseende byggnader", "id": "8030", "typ": "Numeriskt_B"},
{"namn": "7.12 Vid beskattningsårets utgång ej återförda värdeminskningsavdrag avseende markanläggningar", "id": "8031", "typ": "Numeriskt_B"},
{"namn": "7.13 Vid restvärdeavskrivning: återförda belopp för av- och nedskrivning, försäljning, utrangering", "id": "8033", "typ": "Numeriskt_B"},
{"namn": "7.14 Avdrag för kapitalförvaltningskostnader har gjorts med", "id": "8034", "typ": "Numeriskt_B"},
{"namn": "Uppdragstagare (t.ex. redovisningskonsult) har biträtt vid upprättandet av årsbokslutet/årsredovisningen: Ja", "id": "8040", "typ": "Str_X"},
{"namn": "Uppdragstagare (t.ex. redovisningskonsult) har biträtt vid upprättandet av årsbokslutet/årsredovisningen: Nej", "id": "8041", "typ": "Str_X"},
{"namn": "Årsredovisningen har varit föremål för revision: Ja", "id": "8044", "typ": "Str_X"},
{"namn": "Årsredovisningen har varit föremål för revision: Nej", "id": "8045", "typ": "Str_X"}],

                                "INK3SU-2013": [
                                {"namn": "Räkenskapsårets början", "id": 7011, "typ": "Datum_A"},
                                {"namn": "Räkenskapsårets slut", "id": "7012", "typ": "Datum_A"},
                                {"namn": "Stiftelsens ändamål - undervisning/utbildning", "id": "8800", "typ": "Str_X"},
                                {"namn": "Stiftelsens ändamål - hjälpverksamhet behövande", "id": "8801", "typ": "Str_X"},
                                {"namn": "Stiftelsens ändamål - Nordiskt samarbete", "id": "8802", "typ": "Str_X"},
                                {"namn": "Stiftelsens ändamål - vetenskaplig forskning", "id": "8803", "typ": "Str_X"},
                                {"namn": "Stiftelsens ändamål - vård/uppfostran av barn", "id": "8804", "typ": "Str_X"},
                                {"namn": "Stiftelsens ändamål - stärka Sveriges försvar", "id": "8805", "typ": "Str_X"},
                                {"namn": "Stiftelsens ändamål - Övriga ändamål", "id": "8840", "typ": "Str_36"},
                                {"namn": "3.1 Beslutad utdelning av bidrag/ stipendier enligt ändamål", "id": "8850", "typ": "Numeriskt_A"},
                                {"namn": "3.2 Kapitalavkastning", "id": "8851", "typ": "Numeriskt_A"},
                                {"namn": "3.3 Kapitalförvaltningskostnader", "id": "8852", "typ": "Numeriskt_A"},
                                {"namn": "3.4 Kostnader för att fullfölja stiftelsens ändamål", "id": "8853", "typ": "Numeriskt_A"},
                                {"namn": "3.5 Beslutad utdelning enligt p. 3.1som hör till föregående års kapitalavkastning", "id": "8854", "typ": "Str_X"},
                                {"namn": "3.6 Uppgifter för verksamhetsstiftelser - Intäkter", "id": "8855", "typ": "Numeriskt_A"},
                                {"namn": "3.7 Uppgifter för verksamhetsstiftelser - Kostnader", "id": "8856", "typ": "Numeriskt_A"},
                                {"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Religiöst", "id": "8820", "typ": "Str_X"},
                                {"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Socialt", "id": "8821", "typ": "Str_X"},
                                {"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Idrottsligt", "id": "8822", "typ": "Str_X"},
                                {"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - vård/uppfostran av barn", "id": "8823", "typ": "Str_X"},
                                {"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - hjälpverksamhet bland behövande", "id": "8824", "typ": "Str_X"},
                                {"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Nordiskt samarbete", "id": "8825", "typ": "Str_X"},
                                {"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Välgörande", "id": "8826", "typ": "Str_X"},
                                {"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Politiskt", "id": "8827", "typ": "Str_X"},
                                {"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Konstnärligt/kulturellt", "id": "8828", "typ": "Str_X"},
                                {"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Undervisning/utbildning", "id": "8829", "typ": "Str_X"},
                                {"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Vetenskaplig forskning", "id": "8830", "typ": "Str_X"},
                                {"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Stärka Sveriges försvar", "id": "8831", "typ": "Str_X"},
                                {"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Övriga ändamål", "id": "8620", "typ": "Str_36"},
                                {"namn": "Föreningar/Trossamfund: Hur stor del av fastigheten används i den egna verksamheten, ange procenttal", "id": "8624", "typ": "Numeriskt_G"},
                                {"namn": "Föreningar/Trossamfund: Hur stor del av fastigheten används i den egna verksamheten, ange yta i kvm", "id": "8625", "typ": "Numeriskt_A"},
                                {"namn": "4.1 Föreningar/Trossamfund: Intäkter under beskattningsåret: Medlemsavgifter", "id": "8640", "typ": "Numeriskt_A"},
                                {"namn": "4.2 Föreningar/Trossamfund: Intäkter under beskattningsåret: Bidrag/gåvor", "id": "8641", "typ": "Numeriskt_A"},
                                {"namn": "4.3 Föreningar/Trossamfund:Intäkter under beskattningsåret: Kapitalavkastning (räntor, utdelningar, ej kapitalvinster)", "id": "8642", "typ": "Numeriskt_A"},
                                {"namn": "4.4 Föreningar/Trossamfund:Intäkter under beskattningsåret: Kapitalvinster", "id": "8643", "typ": "Numeriskt_A"},
                                {"namn": "4.5 Föreningar/Trossamfund: Skattefri rörelse (naturlig anknytning/hävd)", "id": "8629", "typ": "Numeriskt_A"},
                                {"namn": "4.6 Föreningar/Trossamfund:Intäkter under beskattningsåret: Skattefri fastighet", "id": "8644", "typ": "Numeriskt_A"},
                                {"namn": "4.7 Föreningar/Trossamfund:Intäkter under beskattningsåret: Övriga intäkter", "id": "8645", "typ": "Numeriskt_A"},
                                {"namn": "4.8 Föreningar/Trossamfund: Kostnader under beskattningsåret Ändamålsenlig verksamhet/ medlemsverksamhet", "id": "8713", "typ": "Numeriskt_A"},
                                {"namn": "4.9 Föreningar/Trossamfund: Kostnader under beskattningsåret: Utdelade bidrag/stipendier enligt ändamålet", "id": "8714", "typ": "Numeriskt_A"},
                                {"namn": "4.10 Föreningar/Trossamfund: Kostnader under beskattningsåret: Kapitalförvaltning", "id": "8715", "typ": "Numeriskt_A"},
                                {"namn": "4.11 Föreningar/Trossamfund: Kostnader under beskattningsåret: Kapitalförluster", "id": "8716", "typ": "Numeriskt_A"},
                                {"namn": "4.12 Föreningar/Trossamfund: Kostnader under beskattningsåret: Skattefri rörelse", "id": "8717", "typ": "Numeriskt_A"},
                                {"namn": "4.13 Föreningar/Trossamfund: Kostnader under beskattningsåret: Skattefri fastighet", "id": "8718", "typ": "Numeriskt_A"},
                                {"namn": "4.14 Föreningar/Trossamfund: Kostnader under beskattningsåret: Övriga kostnader", "id": "8719", "typ": "Numeriskt_A"}],

				"INK4R-2013": [
                                {"id": 7011, "namn": "Räkenskapsår Fr.o.m",  "typ": "Datum_A"}, 
                                {"id": 7012, "namn": "Räkenskapsår T.o.m",  "typ": "Datum_A"}, 

                                {"id": 7201, "namn": "2.1", "typ": "Numeriskt_A"}, 
                                {"id": 7202, "namn": "2.2", "typ": "Numeriskt_A"}, 
                                
                                {"id": 7214, "namn": "2.3", "typ": "Numeriskt_A"}, 
                                {"id": 7215, "namn": "2.4", "typ": "Numeriskt_A"}, 
                                {"id": 7216, "namn": "2.5", "typ": "Numeriskt_A"}, 
                                {"id": 7217, "namn": "2.6", "typ": "Numeriskt_A"},

                                {"id": 7236, "namn": "2.7", "typ": "Numeriskt_A"},
                                {"id": 7232, "namn": "2.8", "typ": "Numeriskt_A"},
                                {"id": 7237, "namn": "2.9", "typ": "Numeriskt_A"},
				{
				"id": 7247, "namn": "2.10", "typ": "Numeriskt_A"},
                                {"id": 7245, "namn": "2.11", "typ": "Numeriskt_A"},
                                {"id": 7246, "namn": "2.12", "typ": "Numeriskt_A"},
                                
                                {"id": 7253, "namn": "2.13", "typ": "Numeriskt_A"},
				
				{"id": 7264, "namn": "2.14", "typ": "Numeriskt_A"},
                                {"id": 7263, "namn": "2.15", "typ": "Numeriskt_A"},
				
				{"id": 7272, "namn": "2.16", "typ": "Numeriskt_A"},
				
				{"id": 7281, "namn": "2.17", "typ": "Numeriskt_A"},
				
				{"id": 7310, "namn": "2.18", "typ": "Numeriskt_A"},
                                {"id": 7311, "namn": "2.19", "typ": "Numeriskt_A"},
                                {"id": 7312, "namn": "2.20", "typ": "Numeriskt_A"},
                                {"id": 7313, "namn": "2.21", "typ": "Numeriskt_A"},
				{"id": 7314, "namn": "2.22", "typ": "Numeriskt_A"},

                                {"id": 7322, "namn": "2.23", "typ": "Numeriskt_A"},
                                {"id": 7323, "namn": "2.24", "typ": "Numeriskt_A"},
				
                                {"id": 7331, "namn": "2.25", "typ": "Numeriskt_A"},
                                {"id": 7332, "namn": "2.26", "typ": "Numeriskt_A"},
                                {"id": 7333, "namn": "2.27", "typ": "Numeriskt_A"},
				
                                {"id": 7353, "namn": "2.28", "typ": "Numeriskt_A"},
                                {"id": 7355, "namn": "2.29", "typ": "Numeriskt_A"},

                                {"id": 7362, "namn": "2.30", "typ": "Numeriskt_A"},
                                {"id": 7363, "namn": "2.31", "typ": "Numeriskt_A"},
                                {"id": 7365, "namn": "2.32", "typ": "Numeriskt_A"},
                                {"id": 7368, "namn": "2.33", "typ": "Numeriskt_A"},

                                {"id": 7371, "namn": "2.34", "typ": "Numeriskt_A"},
                                {"id": 7370, "namn": "2.35", "typ": "Numeriskt_A"},

                                {"id": 7410, "namn": "3.1+", "typ": "Numeriskt_A"},
                                
                                {"id": 7411, "namn": "3.2+", "typ": "Numeriskt_A"},
                                {"id": 7510, "namn": "3.2-", "typ": "Numeriskt_A"},
                                
                                {"id": 7412, "namn": "3.3+", "typ": "Numeriskt_A"},
                                {"id": 7413, "namn": "3.4+", "typ": "Numeriskt_A"},
                                {"id": 7511, "namn": "3.5-", "typ": "Numeriskt_A"},
                                {"id": 7512, "namn": "3.6-", "typ": "Numeriskt_A"},
                                {"id": 7513, "namn": "3.7-", "typ": "Numeriskt_A"},
                                {"id": 7514, "namn": "3.8-", "typ": "Numeriskt_A"},
                                {"id": 7515, "namn": "3.9-", "typ": "Numeriskt_A"},
                                {"id": 7535, "namn": "3.10-", "typ": "Numeriskt_A"},
				
				{"id": 7414, "namn": "3.11+", "typ": "Numeriskt_A"},
                                {"id": 7518, "namn": "3.11+", "typ": "Numeriskt_A"},
                                
                                {"id": 7415, "namn": "3.12+", "typ": "Numeriskt_A"},
                                {"id": 7519, "namn": "3.12-", "typ": "Numeriskt_A"},
                                
                                {"id": 7416, "namn": "3.13+", "typ": "Numeriskt_A"},
                                {"id": 7520, "namn": "3.13-", "typ": "Numeriskt_A"},
                                
				{"id": 7417, "namn": "3.14+", "typ": "Numeriskt_A"},

                                {"id": 7521, "namn": "3.15-", "typ": "Numeriskt_A"},
				{"id": 7522, "namn": "3.16", "typ": "Numeriskt_A"},

                                {"id": 7427, "namn": "3.17+", "typ": "Numeriskt_B"},
				{"id": 7537, "namn": "3.17-", "typ": "Numeriskt_B"},

                                {"id": 7450, "namn": "3.18=+", "typ": "Numeriskt_B"},
                                {"id": 7550, "namn": "3.19=-", "typ": "Numeriskt_B"}],

				"INK4S-2013": [
                                {"id": 7011, "namn": "Räkenskapsår Fr.o.m",  "typ": "Datum_A"}, 
                                {"id": 7012, "namn": "Räkenskapsår T.o.m",  "typ": "Datum_A"}, 

                                {"id": 7650, "namn": "4.1+", "typ": "Numeriskt_B"},
                                {"id": 7750, "namn": "4.2-", "typ": "Numeriskt_B"},
                                
                                {"id": 7652, "namn": "4.3a+", "typ": "Numeriskt_A"},
                                {"id": 7653, "namn": "4.3b+", "typ": "Numeriskt_A"},
                                
                                {"id": 7761, "namn": "4.4a-", "typ": "Numeriskt_B"},
                                {"id": 7764, "namn": "4.4b-", "typ": "Numeriskt_A"},
                                
                                {"id": 7752, "namn": "4.5a-", "typ": "Numeriskt_A"},
                                {"id": 7754, "namn": "4.5b-", "typ": "Numeriskt_A"},
                                
                                {"id": 7662, "namn": "4.6a+", "typ": "Numeriskt_A"},
                                {"id": 7668, "namn": "4.6b+", "typ": "Numeriskt_A"},
                                {"id": 7665, "namn": "4.6c+", "typ": "Numeriskt_A"},
                                
                                {"id": 7766, "namn": "4.7a-", "typ": "Numeriskt_A"},
                                
                                {"id": 7741, "namn": "4.8a-", "typ": "Numeriskt_A"},
                                {"id": 7642, "namn": "4.8b+", "typ": "Numeriskt_B"},
                                {"id": 7641, "namn": "4.8c+", "typ": "Numeriskt_B"},
                                {"id": 7742, "namn": "4.8d-", "typ": "Numeriskt_A"},

                                {"id": 7666, "namn": "4.9+", "typ": "Numeriskt_B"},
                                {"id": 7765, "namn": "4.9-", "typ": "Numeriskt_B"},

                                {"id": 7767, "namn": "4.10a-", "typ": "Numeriskt_B"},
                                {"id": 7669, "namn": "4.10b+", "typ": "Numeriskt_B"},
                                
                                {"id": 7768, "namn": "4.11a-", "typ": "Numeriskt_A"},
                                {"id": 7643, "namn": "4.11b+", "typ": "Numeriskt_A"},

                                {"id": 7670, "namn": "4.12+", "typ": "Numeriskt_A"},
                                {"id": 7770, "namn": "4.13-", "typ": "Numeriskt_A"},
                                
                                {"id": 8020, "namn": "4.14", "typ": "Numeriskt_A"},
                                {"id": 8021, "namn": "4.15", "typ": "Numeriskt_A"},
                                
                                {"id": 8040, "namn": "Redovisningskonsult JA", "typ": "Str_X"},
                                {"id": 8041, "namn": "Redovisningskonsult NEJ", "typ": "Str_X"},

                                {"id": 8044, "namn": "Revision JA", "typ": "Str_X"},
				{"id": 8045, "namn": "Revision NEJ", "typ": "Str_X"}],

				"INK4DU-2013": [
                                {"id": 7011, "namn": "Räkenskapsår Fr.o.m",  "typ": "Datum_A"}, 
                                {"id": 7012, "namn": "Räkenskapsår T.o.m",  "typ": "Datum_A"}, 

                                {"id": 8100, "namn": "Person-/organisationsnr", "typ": "Orgnr_Id"},
                                {"id": 8101, "namn": "Resultat summa överskott", "typ": "Numeriskt_B"},
                                {"id": 8102, "namn": "Resultat summa underskott", "typ": "Numeriskt_B"},
                                {"id": 8103, "namn": "Delägarens tillskott", "typ": "Numeriskt_B"},
                                {"id": 8104, "namn": "Delägarens uttag", "typ": "Numeriskt_B"},
                                {"id": 8105, "namn": "Andel avdragen arbetsgivaravgift", "typ": "Numeriskt_B"},

                                {"id": 8100, "namn": "Person-/organisationsnr", "typ": "Orgnr_Id"},
                                {"id": 8101, "namn": "Resultat summa överskott", "typ": "Numeriskt_B"},
                                {"id": 8102, "namn": "Resultat summa underskott", "typ": "Numeriskt_B"},
                                {"id": 8103, "namn": "Delägarens tillskott", "typ": "Numeriskt_B"},
                                {"id": 8104, "namn": "Delägarens uttag", "typ": "Numeriskt_B"},
                                {"id": 8105, "namn": "Andel avdragen arbetsgivaravgift", "typ": "Numeriskt_B"},

                                {"id": 8100, "namn": "Person-/organisationsnr", "typ": "Orgnr_Id"},
                                {"id": 8101, "namn": "Resultat summa överskott", "typ": "Numeriskt_B"},
                                {"id": 8102, "namn": "Resultat summa underskott", "typ": "Numeriskt_B"},
                                {"id": 8103, "namn": "Delägarens tillskott", "typ": "Numeriskt_B"},
                                {"id": 8104, "namn": "Delägarens uttag", "typ": "Numeriskt_B"},
                                {"id": 8105, "namn": "Andel avdragen arbetsgivaravgift", "typ": "Numeriskt_B"},

                                {"id": 8100, "namn": "Person-/organisationsnr", "typ": "Orgnr_Id"},
                                {"id": 8101, "namn": "Resultat summa överskott", "typ": "Numeriskt_B"},
                                {"id": 8102, "namn": "Resultat summa underskott", "typ": "Numeriskt_B"},
                                {"id": 8103, "namn": "Delägarens tillskott", "typ": "Numeriskt_B"},
                                {"id": 8104, "namn": "Delägarens uttag", "typ": "Numeriskt_B"},
                                {"id": 8105, "namn": "Andel avdragen arbetsgivaravgift", "typ": "Numeriskt_B"},

                                {"id": 8100, "namn": "Person-/organisationsnr", "typ": "Orgnr_Id"},
                                {"id": 8101, "namn": "Resultat summa överskott", "typ": "Numeriskt_B"},
                                {"id": 8102, "namn": "Resultat summa underskott", "typ": "Numeriskt_B"},
                                {"id": 8103, "namn": "Delägarens tillskott", "typ": "Numeriskt_B"},
                                {"id": 8104, "namn": "Delägarens uttag", "typ": "Numeriskt_B"},
                                {"id": 8105, "namn": "Andel avdragen arbetsgivaravgift", "typ": "Numeriskt_B"},

                                {"id": 8100, "namn": "Person-/organisationsnr", "typ": "Orgnr_Id"},
                                {"id": 8101, "namn": "Resultat summa överskott", "typ": "Numeriskt_B"},
                                {"id": 8102, "namn": "Resultat summa underskott", "typ": "Numeriskt_B"},
                                {"id": 8103, "namn": "Delägarens tillskott", "typ": "Numeriskt_B"},
                                {"id": 8104, "namn": "Delägarens uttag", "typ": "Numeriskt_B"},
                                {"id": 8105, "namn": "Andel avdragen arbetsgivaravgift", "typ": "Numeriskt_B"},

                                {"id": 8100, "namn": "Person-/organisationsnr", "typ": "Orgnr_Id"},
                                {"id": 8101, "namn": "Resultat summa överskott", "typ": "Numeriskt_B"},
                                {"id": 8102, "namn": "Resultat summa underskott", "typ": "Numeriskt_B"},
                                {"id": 8103, "namn": "Delägarens tillskott", "typ": "Numeriskt_B"},
                                {"id": 8104, "namn": "Delägarens uttag", "typ": "Numeriskt_B"},
                                {"id": 8105, "namn": "Andel avdragen arbetsgivaravgift", "typ": "Numeriskt_B"},

                                {"id": 8100, "namn": "Person-/organisationsnr", "typ": "Orgnr_Id"},
                                {"id": 8101, "namn": "Resultat summa överskott", "typ": "Numeriskt_B"},
                                {"id": 8102, "namn": "Resultat summa underskott", "typ": "Numeriskt_B"},
                                {"id": 8103, "namn": "Delägarens tillskott", "typ": "Numeriskt_B"},
                                {"id": 8104, "namn": "Delägarens uttag", "typ": "Numeriskt_B"},
                                {"id": 8105, "namn": "Andel avdragen arbetsgivaravgift", "typ": "Numeriskt_B"},

                                {"id": 8100, "namn": "Person-/organisationsnr", "typ": "Orgnr_Id"},
                                {"id": 8101, "namn": "Resultat summa överskott", "typ": "Numeriskt_B"},
                                {"id": 8102, "namn": "Resultat summa underskott", "typ": "Numeriskt_B"},
                                {"id": 8103, "namn": "Delägarens tillskott", "typ": "Numeriskt_B"},
                                {"id": 8104, "namn": "Delägarens uttag", "typ": "Numeriskt_B"},
                                {"id": 8105, "namn": "Andel avdragen arbetsgivaravgift", "typ": "Numeriskt_B"},

                                {"id": 8100, "namn": "Person-/organisationsnr", "typ": "Orgnr_Id"},
                                {"id": 8101, "namn": "Resultat summa överskott", "typ": "Numeriskt_B"},
                                {"id": 8102, "namn": "Resultat summa underskott", "typ": "Numeriskt_B"},
                                {"id": 8103, "namn": "Delägarens tillskott", "typ": "Numeriskt_B"},
                                {"id": 8104, "namn": "Delägarens uttag", "typ": "Numeriskt_B"},
                                {"id": 8105, "namn": "Andel avdragen arbetsgivaravgift", "typ": "Numeriskt_B"},

                                {"id": 8100, "namn": "Person-/organisationsnr", "typ": "Orgnr_Id"},
                                {"id": 8101, "namn": "Resultat summa överskott", "typ": "Numeriskt_B"},
                                {"id": 8102, "namn": "Resultat summa underskott", "typ": "Numeriskt_B"},
                                {"id": 8103, "namn": "Delägarens tillskott", "typ": "Numeriskt_B"},
                                {"id": 8104, "namn": "Delägarens uttag", "typ": "Numeriskt_B"},
                                {"id": 8105, "namn": "Andel avdragen arbetsgivaravgift", "typ": "Numeriskt_B"},

                                {"id": 8100, "namn": "Person-/organisationsnr", "typ": "Orgnr_Id"},
                                {"id": 8101, "namn": "Resultat summa överskott", "typ": "Numeriskt_B"},
                                {"id": 8102, "namn": "Resultat summa underskott", "typ": "Numeriskt_B"},
                                {"id": 8103, "namn": "Delägarens tillskott", "typ": "Numeriskt_B"},
                                {"id": 8104, "namn": "Delägarens uttag", "typ": "Numeriskt_B"},
                                {"id": 8105, "namn": "Andel avdragen arbetsgivaravgift", "typ": "Numeriskt_B"},

                                {"id": 8100, "namn": "Person-/organisationsnr", "typ": "Orgnr_Id"},
                                {"id": 8101, "namn": "Resultat summa överskott", "typ": "Numeriskt_B"},
                                {"id": 8102, "namn": "Resultat summa underskott", "typ": "Numeriskt_B"},
                                {"id": 8103, "namn": "Delägarens tillskott", "typ": "Numeriskt_B"},
                                {"id": 8104, "namn": "Delägarens uttag", "typ": "Numeriskt_B"},
                                {"id": 8105, "namn": "Andel avdragen arbetsgivaravgift", "typ": "Numeriskt_B"},

                                {"id": 8100, "namn": "Person-/organisationsnr", "typ": "Orgnr_Id"},
                                {"id": 8101, "namn": "Resultat summa överskott", "typ": "Numeriskt_B"},
                                {"id": 8102, "namn": "Resultat summa underskott", "typ": "Numeriskt_B"},
                                {"id": 8103, "namn": "Delägarens tillskott", "typ": "Numeriskt_B"},
                                {"id": 8104, "namn": "Delägarens uttag", "typ": "Numeriskt_B"},
                                {"id": 8105, "namn": "Andel avdragen arbetsgivaravgift", "typ": "Numeriskt_B"},

                                {"id": 8100, "namn": "Person-/organisationsnr", "typ": "Orgnr_Id"},
                                {"id": 8101, "namn": "Resultat summa överskott", "typ": "Numeriskt_B"},
                                {"id": 8102, "namn": "Resultat summa underskott", "typ": "Numeriskt_B"},
                                {"id": 8103, "namn": "Delägarens tillskott", "typ": "Numeriskt_B"},
                                {"id": 8104, "namn": "Delägarens uttag", "typ": "Numeriskt_B"},
                                {"id": 8105, "namn": "Andel avdragen arbetsgivaravgift", "typ": "Numeriskt_B"},

                                {"id": 8100, "namn": "Person-/organisationsnr", "typ": "Orgnr_Id"},
                                {"id": 8101, "namn": "Resultat summa överskott", "typ": "Numeriskt_B"},
                                {"id": 8102, "namn": "Resultat summa underskott", "typ": "Numeriskt_B"},
                                {"id": 8103, "namn": "Delägarens tillskott", "typ": "Numeriskt_B"},
                                {"id": 8104, "namn": "Delägarens uttag", "typ": "Numeriskt_B"},
                                {"id": 8105, "namn": "Andel avdragen arbetsgivaravgift", "typ": "Numeriskt_B"}]
                        };

