var uppifter = { 
	"INK2R-2014": [
		{"namn": "Räkenskapsårets början", "id": "7011", "typ": "Datum_D"},
		{"namn": "Räkenskapsårets slut", "id": "7012", "typ": "Datum_D"},
		{"namn": "2.1 Immateriella anläggningstillgångar Koncessioner, patent, licenser, varumärken, hyresrätter, goodwill och liknande rättigheter", "id": "7201", "typ": "Numeriskt_A"},
		{"namn": "2.2 Immateriella anläggningstillgångar Förskott avseende immateriella anläggningstillgångar", "id": "7202", "typ": "Numeriskt_A"},
		{"namn": "2.3 Materiella anläggningstillgångar Byggnader och mark", "id": "7214", "typ": "Numeriskt_A"},
		{"namn": "2.4 Materiella anläggningstillgångar Maskiner, inventarier och övriga materiella anläggningstillgångar", "id": "7215", "typ": "Numeriskt_A"},
		{"namn": "2.5 Materiella anläggningstillgångar Förbättringsutgifter på annans fastighet", "id": "7216", "typ": "Numeriskt_A"},
		{"namn": "2.6 Materiella anläggningstillgångar Pågående nyanläggningar och förskott avseende materiella anläggningstillgångar", "id": "7217", "typ": "Numeriskt_A"},
		{"namn": "2.7 Finansiella anläggningstillgångar Andelar i koncernföretag", "id": "7230", "typ": "Numeriskt_A"},
		{"namn": "2.8 Finansiella anläggningstillgångar Andelar i intresseföretag", "id": "7231", "typ": "Numeriskt_A"},
		{"namn": "2.9 Finansiella anläggningstillgångar Fordringar hos koncern- och intresseföretag", "id": "7232", "typ": "Numeriskt_A"},
		{"namn": "2.10 Finansiella anläggningstillgångar Andra långfristiga värdepappersinnehav", "id": "7233", "typ": "Numeriskt_A"}, 
        {"namn": "2.11 Finansiella anläggningstillgångar Lån till delägare eller närstående", "id": "7234", "typ": "Numeriskt_A"},
		{"namn": "2.12 Finansiella anläggningstillgångar Andra långfristiga fordringar", "id": "7235", "typ": "Numeriskt_A"},
		{"namn": "2.13 Varulager Råvaror och förnödenheter", "id": "7241", "typ": "Numeriskt_A"},
		{"namn": "2.14 Varulager Varor under tillverkning", "id": "7242", "typ": "Numeriskt_A"},
		{"namn": "2.15 Varulager Färdiga varor och handelsvaror", "id": "7243", "typ": "Numeriskt_A"},
		{"namn": "2.16 Varulager Övriga lagertillgångar", "id": "7244", "typ": "Numeriskt_A"},
		{"namn": "2.17 Varulager Pågående arbeten för annans räkning", "id": "7245", "typ": "Numeriskt_A"},
		{"namn": "2.18 Varulager Förskott till leverantörer", "id": "7246", "typ": "Numeriskt_A"},
		{"namn": "2.19 Kortfristiga fordringar Kundfordringar", "id": "7251", "typ": "Numeriskt_A"},
		{"namn": "2.20 Kortfristiga fordringar Fordringar hos koncern- och intresseföretag", "id": "7252", "typ": "Numeriskt_A"},
		{"namn": "2.21 Kortfristiga fordringar Övriga fordringar", "id": "7261", "typ": "Numeriskt_A"},
		{"namn": "2.22 Kortfristiga fordringar Upparbetad men ej fakturerad intäkt", "id": "7262", "typ": "Numeriskt_A"},
		{"namn": "2.23 Kortfristiga fordringar Förutbetalda kostnader och upplupna intäkter", "id": "7263", "typ": "Numeriskt_A"},
		{"namn": "2.24 Kortfristiga placeringar Andelar i koncernföretag", "id": "7270", "typ": "Numeriskt_A"},
		{"namn": "2.25 Kortfristiga placeringar Övriga kortfristiga placeringar", "id": "7271", "typ": "Numeriskt_A"},
		{"namn": "2.26 Kassa och bank Kassa, bank och redovisningsmedel", "id": "7281", "typ": "Numeriskt_A"},
		{"namn": "2.27 Eget kapital Bundet eget kapital", "id": "7301", "typ": "Numeriskt_A"},
		{"namn": "2.28 Eget kapital Fritt eget kapital", "id": "7302", "typ": "Numeriskt_A"},
		{"namn": "2.29 Obeskattade reserver Periodiseringsfonder", "id": "7321", "typ": "Numeriskt_A"},
		{"namn": "2.30 Obeskattade reserver Ackumulerade överavskrivningar", "id": "7322", "typ": "Numeriskt_A"},
		{"namn": "2.31 Obeskattade reserver Övriga obeskattade reserver", "id": "7323", "typ": "Numeriskt_A"},
		{"namn": "2.32 Avsättningar Avsättningar för pensioner och liknande förpliktelser enligt lag (1967:531)...", "id": "7331", "typ": "Numeriskt_A"},
		{"namn": "2.33 Avsättningar Övriga avsättningar för pensioner och liknande förpliktelser", "id": "7332", "typ": "Numeriskt_A"},
		{"namn": "2.34 Avsättningar Övriga avsättningar", "id": "7333", "typ": "Numeriskt_A"},
		{"namn": "2.35 Långfristiga skulder Obligationslån", "id": "7350", "typ": "Numeriskt_A"},
		{"namn": "2.36 Långfristiga skulder Checkräkningskredit", "id": "7351", "typ": "Numeriskt_A"},
		{"namn": "2.37 Långfristiga skulder Övriga skulder till kreditinstitut", "id": "7352", "typ": "Numeriskt_A"},
		{"namn": "2.38 Långfristiga skulder Skulder till koncern- och intresseföretag", "id": "7353", "typ": "Numeriskt_A"},
		{"namn": "2.39 Långfristiga skulder Övriga skulder", "id": "7354", "typ": "Numeriskt_A"},
		{"namn": "2.40 Kortfristiga skulder Checkräkningskredit", "id": "7360", "typ": "Numeriskt_A"},
		{"namn": "2.41 Kortfristiga skulder Övriga skulder till kreditinstitut", "id": "7361", "typ": "Numeriskt_A"},
		{"namn": "2.42 Kortfristiga skulder Förskott från kunder", "id": "7362", "typ": "Numeriskt_A"},
		{"namn": "2.43 Kortfristiga skulder Pågående arbeten för annans räkning", "id": "7363", "typ": "Numeriskt_A"},
		{"namn": "2.44 Kortfristiga skulder Fakturerad men ej upparbetad intäkt", "id": "7364", "typ": "Numeriskt_A"},
		{"namn": "2.45 Kortfristiga skulder Leverantörsskulder", "id": "7365", "typ": "Numeriskt_A"},
		{"namn": "2.46 Kortfristiga skulder Växelskulder", "id": "7366", "typ": "Numeriskt_A"},
		{"namn": "2.47 Kortfristiga skulder Skulder till koncern- och intresseföretag", "id": "7367", "typ": "Numeriskt_A"},
		{"namn": "2.48 Kortfristiga skulder Skattesskulder", "id": "7368", "typ": "Numeriskt_A"},
		{"namn": "2.49 Kortfristiga skulder Övriga skulder", "id": "7369", "typ": "Numeriskt_A"},
		{"namn": "2.50 Kortfristiga skulder Upplupna kostnader och förutbetalda intäkter", "id": "7370", "typ": "Numeriskt_A"},
		{"namn": "3.1 Nettoomsättning", "id": "7410", "typ": "Numeriskt_A"},
		{"namn": "3.2 Förändring av lager av produkter i arbete, färdiga varor och pågående arbete för annans räkning. +", "id": "7411", "typ": "Numeriskt_A"},
		{"namn": "3.2 Förändring av lager av produkter i arbete, färdiga varor och pågående arbete för annans räkning. -", "id": "7510", "typ": "Numeriskt_A"},
		{"namn": "3.3 Aktiverat arbete för egen räkning", "id": "7412", "typ": "Numeriskt_A"},
		{"namn": "3.4 Övriga rörelseintäkter", "id": "7413", "typ": "Numeriskt_A"},
		{"namn": "3.5 Råvaror och förnödenheter", "id": "7511", "typ": "Numeriskt_A"},
		{"namn": "3.6 Handelsvaror", "id": "7512", "typ": "Numeriskt_A"},
		{"namn": "3.7 Övriga externa kostnader", "id": "7513", "typ": "Numeriskt_A"},
		{"namn": "3.8 Personalkostnader", "id": "7514", "typ": "Numeriskt_A"},
		{"namn": "3.9 Av- och nedskrivningar av materiella och immateriella anläggningstillgångar", "id": "7515", "typ": "Numeriskt_A"},
		{"namn": "3.10 Nedskrivningar av omsättningstillgångar utöver normala nedskrivningar", "id": "7516", "typ": "Numeriskt_A"},
		{"namn": "3.11 Övriga rörelsekostnader", "id": "7517", "typ": "Numeriskt_A"},
		{"namn": "3.12 Resultat från andelar i koncernföretag +", "id": "7414", "typ": "Numeriskt_A"},
		{"namn": "3.12 Resultat från andelar i koncernföretag -", "id": "7518", "typ": "Numeriskt_A"},
		{"namn": "3.13 Resultat från andelar i intresseföretag +", "id": "7415", "typ": "Numeriskt_A"},
		{"namn": "3.13 Resultat från andelar i intresseföretag -", "id": "7519", "typ": "Numeriskt_A"},
		{"namn": "3.14 Resultat från övriga finansiella anläggningstillgångar +", "id": "7416", "typ": "Numeriskt_A"},
		{"namn": "3.14 Resultat från övriga finansiella anläggningstillgångar -", "id": "7520", "typ": "Numeriskt_A"},
		{"namn": "3.15 Övriga ränteintäkter och liknande resultatposter", "id": "7417", "typ": "Numeriskt_A"},
		{"namn": "3.16 Nedskrivning av finansiella anläggningstillgångar och kortfristiga placeringar", "id": "7521", "typ": "Numeriskt_A"},
		{"namn": "3.17 Räntekostnader och liknande resultatposter", "id": "7522", "typ": "Numeriskt_A"},
		{"namn": "3.18 Extraordinära intäkter", "id": "7418", "typ": "Numeriskt_A"},
		{"namn": "3.19 Extraordinära kostnader", "id": "7523", "typ": "Numeriskt_A"},
		{"namn": "3.20 Lämnade koncernbidrag", "id": "7524", "typ": "Numeriskt_A"},
		{"namn": "3.21 Mottagna koncernbidrag", "id": "7419", "typ": "Numeriskt_A"},
		{"namn": "3.22 Återföring av periodiseringsfond", "id": "7420", "typ": "Numeriskt_B"},
		{"namn": "3.23 Avsättning till periodiseringsfond", "id": "7525", "typ": "Numeriskt_B"},
		{"namn": "3.24 Förändring av överavskrivningar +", "id": "7421", "typ": "Numeriskt_A"},
		{"namn": "3.24 Förändring av överavskrivningar -", "id": "7526", "typ": "Numeriskt_A"},
		{"namn": "3.25 Övriga bokslutsdispositioner +", "id": "7422", "typ": "Numeriskt_A"},
		{"namn": "3.25 Övriga bokslutsdispositioner -", "id": "7527", "typ": "Numeriskt_A"},
		{"namn": "3.26 Skatt på årets resultat", "id": "7528", "typ": "Numeriskt_A"},
		{"namn": "3.27 Årets resultat, vinst (flyttas till p. 4.1)", "id": "7450", "typ": "Numeriskt_B"},
		{"namn": "3.28 Årets resultat, förlust (flyttas till p. 4.2)", "id": "7550", "typ": "Numeriskt_B"}
	],
	"INK2S-2014": [
		{"namn": "4.1 Årets resultat, vinst", "id": "7650", "typ": "Numeriskt_B"},
		{"namn": "4.2 Årets resultat, förlust", "id": "7750", "typ": "Numeriskt_B"},
		{"namn": "4.3a. Bokförda kostnader som inte ska dras av: a. Skatt på årets resultat", "id": "7651", "typ": "Numeriskt_A"},
		{"namn": "b. Bokförda kostnader som inte ska dras av: b. Nedskrivning av finansiella tillgångar", "id": "7652", "typ": "Numeriskt_A"},
		{"namn": "c. Bokförda kostnader som inte ska dras av: c. Andra bokförda kostnader", "id": "7653", "typ": "Numeriskt_A"},
		{"namn": "4.4a. Kostnader som ska dras av men som inte ingår i det redovisade resultatet: a. Lämnade koncernbidrag", "id": "7751", "typ": "Numeriskt_A"},
		{"namn": "b. Kostnader som ska dras av men som inte ingår i det redovisade resultatet: b. Andra ej bokförda kostnader", "id": "7764", "typ": "Numeriskt_A"},
		{"namn": "4.5a. Bokförda intäkter som inte ska tas upp: a. Ackordsvinster", "id": "7752", "typ": "Numeriskt_A"},
		{"namn": "b. Bokförda intäkter som inte ska tas upp: b. Utdelning", "id": "7753", "typ": "Numeriskt_A"},
		{"namn": "c. Bokförda intäkter som inte ska tas upp: c. Andra bokförda intäkter", "id": "7754", "typ": "Numeriskt_A"},
		{"namn": "4.6a. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet: a. Beräknad schablonintäkt på kvarvarande periodiseringsfonder vid beskattningsårets ingång", "id": "7654", "typ": "Numeriskt_B"},
		{"namn": "b. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet: b. Beräknad schablonintäkt på fondandelar ägda vid ingången av kalenderåret", "id": "7668", "typ": "Numeriskt_A"},
		{"namn": "c. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet: c. Mottagna koncernbidrag", "id": "7655", "typ": "Numeriskt_A"},
		{"namn": "d. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet: d. Intäkt negativ justerad anskaffningsutgift", "id": "7667", "typ": "Numeriskt_A"},
		{"namn": "e. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet: e. Andra ej bokförda intäkter", "id": "7665", "typ": "Numeriskt_A"},
		{"namn": "4.7a. Avyttring av delägarrätter: a. Bokförd vinst", "id": "7755", "typ": "Numeriskt_B"},
		{"namn": "b. Avyttring av delägarrätter: b. Bokförd förlust", "id": "7656", "typ": "Numeriskt_B"},
		{"namn": "c. Avyttring av delägarrätter: c. Uppskov med kapitalvinst enligt blankett N4", "id": "7756", "typ": "Numeriskt_B"},
		{"namn": "d. Avyttring av delägarrätter: d. Återfört uppskov med kapitalvinst enligt blankett N4", "id": "7657", "typ": "Numeriskt_B"},
		{"namn": "e. Avyttring av delägarrätter: e. Kapitalvinst för beskattningsåret", "id": "7658", "typ": "Numeriskt_B"},
		{"namn": "f. Avyttring av delägarrätter: f. Kapitalförlust som ska dras av", "id": "7757", "typ": "Numeriskt_B"},
		{"namn": "4.8a. Andel i handelsbolag (inkl. avyttring): a. Bokförd intäkt/vinst", "id": "7758", "typ": "Numeriskt_B"},
		{"namn": "b. Andel i handelsbolag (inkl. avyttring): b. Skattemässigt överskott enligt N3B", "id": "7659", "typ": "Numeriskt_B"},
		{"namn": "c. Andel i handelsbolag (inkl. avyttring): c. Bokförd kostnad/förlust", "id": "7660", "typ": "Numeriskt_B"},
		{"namn": "d. Andel i handelsbolag (inkl. avyttring): d. Skattemässigt underskott enligt N3B", "id": "7759", "typ": "Numeriskt_B"},
		{"namn": "4.9 Skattemässig justering av bokfört resultat för avskrivningar på byggnader och annan fast egendom samt restvärdesavskrivning på maskiner och inventarier (+)", "id": "7666", "typ": "Numeriskt_B"},
		{"namn": "4.9 Skattemässig justering av bokfört resultat för avskrivningar på byggnader och annan fast egendom samt restvärdesavskrivning på maskiner och inventarier (-)", "id": "7765", "typ": "Numeriskt_B"},
		{"namn": "4.10 Skattemässig korrigering av bokfört resultat vid avyttring av näringsfastighet och näringsbostadsrätt: +", "id": "7661", "typ": "Numeriskt_B"},
		{"namn": "4.10 Skattemässig korrigering av bokfört resultat vid avyttring av näringsfastighet och näringsbostadsrätt: -", "id": "7760", "typ": "Numeriskt_B"},
		{"namn": "4.11 Skogs-/substansminskningsavdrag (specificeras på blankett N8)", "id": "7761", "typ": "Numeriskt_B"},
		{"namn": "4.12 Återföringar vid avyttring av fastighet t.ex. värdeminskningsavdrag, skogsavdrag och substansminskningsavdrag...", "id": "7662", "typ": "Numeriskt_A"},
		{"namn": "4.13 Andra skattemässiga justeringar av resultatet: +", "id": "7663", "typ": "Numeriskt_B"},
		{"namn": "4.13 Andra skattemässiga justeringar av resultatet: -", "id": "7762", "typ": "Numeriskt_B"},
		{"namn": "4.14a. Underskott: a. Outnyttjat underskott från föregående år", "id": "7763", "typ": "Numeriskt_B"},
		{"namn": "b. Underskott: b. Reduktion av underskott med hänsyn till exempelvis ägarförändring eller ackord", "id": "7664", "typ": "Numeriskt_A"},
		{"namn": "4.15 Överskott (flyttas till p. 1.1 på sid. 1)", "id": "7670", "typ": "Numeriskt_B"},
		{"namn": "4.16 Underskott (flyttas till p. 1.2 på sid. 1)", "id": "7770", "typ": "Numeriskt_B"},
		{"namn": "4.17 Årets begärda och tidigare års medgivna värdeminskningsavdrag på byggnader...", "id": "8020", "typ": "Numeriskt_A"},
		{"namn": "4.18 Årets begärda och tidigare års medgivna värdeminskningsavdrag på markanläggningar...", "id": "8021", "typ": "Numeriskt_A"},
		{"namn": "4.19 Vid restvärdesavskrivning:återförda belopp för av- och nedskrivning,försäljning, utrangering", "id": "8023", "typ": "Numeriskt_B"},
		{"namn": "4.20 Lån från aktieägare (fysisk person) vid räkenskapsårets utgång", "id": "8026", "typ": "Numeriskt_B"},
		{"namn": "4.21 Pensionskostnader (som ingår i p. 3.8)", "id": "8022", "typ": "Numeriskt_A"},
		{"namn": "Uppdragstagare (t.ex.) redovisningskonsult) har biträtt vid upprättandet av årsredovisningen: Ja", "id": "8040", "typ": "Str_X"},
		{"namn": "Uppdragstagare (t.ex.) redovisningskonsult) har biträtt vid upprättandet av årsredovisningen: Nej", "id": "8041", "typ": "Str_X"},
		{"namn": "Årsredovisningen har varit föremål för revision: Ja", "id": "8044", "typ": "Str_X"},
		{"namn": "Årsredovisningen har varit föremål för revision: Nej", "id": "8045", "typ": "Str_X"}            
    ],
	"INK3-2014": [
		{"namn": "Räkenskapsårets början", "id": "7011", "typ": "Datum_D"},
		{"namn": "Räkenskapsårets slut", "id": "7012", "typ": "Datum_D"},
		{"namn": "1.1 Överskott", "id": "7106", "typ": "Numeriskt_B"},
		{"namn": "1.2 Underskott", "id": "7116", "typ": "Numeriskt_B"},
		{"namn": "1.3 Underlag för särskild löneskatt på pensionskostnader", "id": "7132", "typ": "Numeriskt_B"},
		{"namn": "1.4 Negativt underlag för särskild löneskatt på pensionskostnader", "id": "7133", "typ": "Numeriskt_B"},
		{"namn": "1.5 Underlag för avkastningsskatt 15%. Försäkringsföretag m.fl. Avsatt till pensioner", "id": "7151", "typ": "Numeriskt_B"},
		{"namn": "1.6 Underlag för avkastningsskatt 30%. Försäkringsföretag m.fl. Utländska kapitalförsäkringar", "id": "7152", "typ": "Numeriskt_B"},
		{"namn": "1.7 Småhus hel avgift", "id": "80", "typ": "Numeriskt_B"},
		{"namn": "1.7 Småhus halv avgift", "id": "82", "typ": "Numeriskt_B"},
		{"namn": "1.8 Hyreshus, bostäder hel avgift", "id": "93", "typ": "Numeriskt_B"},
		{"namn": "1.8 Hyreshus, bostäder halv avgift", "id": "94", "typ": "Numeriskt_B"},
		{"namn": "1.9 Småhus/ägarlägenhet: tomtmark, byggnad under uppförande", "id": "84", "typ": "Numeriskt_B"},
		{"namn": "1.10 Hyreshus: tomtmark, bostäder under uppförande", "id": "86", "typ": "Numeriskt_B"},
		{"namn": "1.11 Hyreshus: lokaler", "id": "95", "typ": "Numeriskt_B"},
		{"namn": "1.12 Industri/elproduktionsenhet, värmekraftverk (utom vindkraftverk)", "id": "96", "typ": "Numeriskt_B"},
		{"namn": "1.13 Elproduktionsenhet, vattenkraftverk", "id": "97", "typ": "Numeriskt_B"},
		{"namn": "1.14 Elproduktionsenhet, vindkraftverk", "id": "98", "typ": "Numeriskt_B"},
		{"namn": "Övriga upplysningar på bilaga", "id": "90", "typ": "Str_X"},
	],

	"INK3K-2014": [
		{"namn": "Räkenskapsårets början", "id": "7011", "typ": "Datum_D"},
		{"namn": "Räkenskapsårets slut", "id": "7012", "typ": "Datum_D"},
		{"namn": "2.1 Resultat från handelsbolagsandel enligt blankett N3B Överskott", "id": "8602", "typ": "Numeriskt_B"},
		{"namn": "2.1 Resultat från handelsbolagsandel enligt blankett N3B Underskott", "id": "8703", "typ": "Numeriskt_B"},
		{"namn": "2.2 Intäktsränta, utdelning eller andra kapitalintäkter", "id": "8600", "typ": "Numeriskt_A"},
		{"namn": "2.3 Kapitalvinst m.m.", "id": "8601", "typ": "Numeriskt_A"},
		{"namn": "2.4 Skuldränta m.m.", "id": "8700", "typ": "Numeriskt_A"},
		{"namn": "2.5 Kostnad för kapitalförvaltning", "id": "8701", "typ": "Numeriskt_A"},
		{"namn": "2.6 Kapitalförlust m.m.", "id": "8702", "typ": "Numeriskt_A"},
		{"namn": "2.7 Lämnade koncernbidrag och uppskov med kapitalvinst enligt N4", "id": "8704", "typ": "Numeriskt_B"},
		{"namn": "2.8 Erhållna koncernbidrag och återfört uppskov av kapitalvinst enligt N4", "id": "8603", "typ": "Numeriskt_B"},
		{"namn": "2.9 Outnyttjat underskott från föregående år", "id": "8705", "typ": "Numeriskt_B"},
		{"namn": "2.10 Beräknad schablonintäkt på fondandelar ägda vid ingången av kalenderåret", "id": "8607", "typ": "Numeriskt_B"},
		{"namn": "2.11 Intäkt negativ justerad anskaffningsutgift", "id": "8606", "typ": "Numeriskt_B"},
		{"namn": "2.12 Återföring av periodiseringsfond", "id": "8604", "typ": "Numeriskt_B"},
		{"namn": "2.13 Beräknad schablonintäkt på kvarvarande periodiserings-fonder vid beskattningsårets ingång", "id": "8605", "typ": "Numeriskt_B"},
		{"namn": "2.14 Avsättning till periodiseringsfond", "id": "8706", "typ": "Numeriskt_B"},
		{"namn": "2.15 Periodiskt understöd i familjestiftelse", "id": "8707", "typ": "Numeriskt_A"},
		{"namn": "2.16 Överskott", "id": "8610", "typ": "Numeriskt_B"},
		{"namn": "2.17 Underskott", "id": "8710", "typ": "Numeriskt_B"}    
	],

	"INK3R-2014": [
		{"namn": "Räkenskapsårets början", "id": "7011", "typ": "Datum_D"},
		{"namn": "Räkenskapsårets slut", "id": "7012", "typ": "Datum_D"},
		{"namn": "5.1 Immateriella anläggningstillgångar", "id": "8720", "typ": "Numeriskt_A"},
		{"namn": "5.2 Byggnader och markanläggningar", "id": "8721", "typ": "Numeriskt_A"},
		{"namn": "5.3 Mark och andra tillgångar som inte får skrivas av", "id": "8722", "typ": "Numeriskt_A"},
		{"namn": "5.4 Maskiner och inventarier", "id": "8723", "typ": "Numeriskt_A"},
		{"namn": "5.5 Finansiella anläggningstillgångar", "id": "8724", "typ": "Numeriskt_A"},
		{"namn": "5.6 Övriga anläggningstillgångar", "id": "8725", "typ": "Numeriskt_A"},
		{"namn": "5.7 Varulager", "id": "8726", "typ": "Numeriskt_A"},
		{"namn": "5.8 Kundfordringar", "id": "8727", "typ": "Numeriskt_A"},
		{"namn": "5.9 Övriga fordringar", "id": "8728", "typ": "Numeriskt_A"},
		{"namn": "5.10 Upplupna intäkter och förutbetalda kostnader", "id": "8729", "typ": "Numeriskt_A"},
		{"namn": "5.11 Kassa och bank", "id": "8730", "typ": "Numeriskt_A"},
		{"namn": "5.12 Eget kapital", "id": "8735", "typ": "Numeriskt_A"},
		{"namn": "5.13 Periodiseringsfonder", "id": "8736", "typ": "Numeriskt_A"},
		{"namn": "5.14 Övriga obeskattade reserver", "id": "8737", "typ": "Numeriskt_A"},
		{"namn": "5.15 Avsättningar för pensioner och liknande förpliktelser", "id": "8738", "typ": "Numeriskt_A"},
		{"namn": "5.16 Övriga avsättningar", "id": "8739", "typ": "Numeriskt_A"},
		{"namn": "5.17 Låneskulder", "id": "8740", "typ": "Numeriskt_A"},
		{"namn": "5.18 Skatteskulder", "id": "8741", "typ": "Numeriskt_A"},
		{"namn": "5.19 Leverantörsskulder", "id": "8742", "typ": "Numeriskt_A"},
		{"namn": "5.20 Övriga skulder", "id": "8743", "typ": "Numeriskt_A"},
		{"namn": "5.21 Upplupna kostnader och förutbetalda intäkter", "id": "8744", "typ": "Numeriskt_A"},
		{"namn": "6.1 Medlemsavgifter (enligt redovisningen)", "id": "8650", "typ": "Numeriskt_A"},
		{"namn": "6.2 Serviceavgifter (enligt redovisningen)", "id": "8651", "typ": "Numeriskt_A"},
		{"namn": "6.2 Serviceavgifter (som ska tas upp/dras av)", "id": "8671", "typ": "Numeriskt_A"},
		{"namn": "6.3 Gåvor och bidrag (enligt redovisningen)", "id": "8652", "typ": "Numeriskt_A"},
		{"namn": "6.3 Gåvor och bidrag (som ska tas upp/dras av)", "id": "8672", "typ": "Numeriskt_A"},
		{"namn": "6.4 Nettoomsättning (enligt redovisningen)", "id": "8653", "typ": "Numeriskt_A"},
		{"namn": "6.4 Nettoomsättning (som ska tas upp/dras av)", "id": "8673", "typ": "Numeriskt_A"},
		{"namn": "6.5 Övriga intäkter (enligt redovisningen)", "id": "8654", "typ": "Numeriskt_A"},
		{"namn": "6.5 Övriga intäkter (som ska tas upp/dras av)", "id": "8674", "typ": "Numeriskt_A"},
		{"namn": "6.6 Varor och legoarbeten (enligt redovisningen)", "id": "8750", "typ": "Numeriskt_A"},
		{"namn": "6.6 Varor och legoarbeten (som ska tas upp/dras av)", "id": "8770", "typ": "Numeriskt_A"},
		{"namn": "6.7 Övriga externa kostnader (enligt redovisningen)", "id": "8751", "typ": "Numeriskt_A"},
		{"namn": "6.7 Övriga externa kostnader (som ska tas upp/dras av)", "id": "8771", "typ": "Numeriskt_A"},
		{"namn": "6.8 Personalkostnader (enligt redovisningen)", "id": "8752", "typ": "Numeriskt_A"},
		{"namn": "6.8 Personalkostnader (som ska tas upp/dras av)", "id": "8772", "typ": "Numeriskt_A"},
		{"namn": "6.9 Av- och nedskrivningar (enligt redovisningen)", "id": "8753", "typ": "Numeriskt_A"},
		{"namn": "6.9 Av- och nedskrivningar (som ska tas upp/dras av)", "id": "8773", "typ": "Numeriskt_A"},
		{"namn": "6.10 Övriga rörelsekostnader (enligt redovisningen)", "id": "8754", "typ": "Numeriskt_A"},
		{"namn": "6.10 Övriga rörelsekostnader (som ska tas upp/dras av)", "id": "8774", "typ": "Numeriskt_A"},
		{"namn": "6.11 Resultat från andelar i koncern- och intresseföretag + (enligt redovisningen)", "id": "8655", "typ": "Numeriskt_B"},
		{"namn": "6.11 Resultat från andelar i koncern- och intresseföretag + (som ska tas upp/dras av)", "id": "8675", "typ": "Numeriskt_B"},
		{"namn": "6.11 Resultat från andelar i koncern- och intresseföretag - (enligt redovisningen)", "id": "8755", "typ": "Numeriskt_B"},
		{"namn": "6.11 Resultat från andelar i koncern- och intresseföretag - (som ska tas upp/dras av)", "id": "8775", "typ": "Numeriskt_B"},
		{"namn": "6.12 Resultat vid avyttring av övriga finansiella anläggningstillgångar + (enligt redovisningen)", "id": "8656", "typ": "Numeriskt_B"},
		{"namn": "6.12 Resultat vid avyttring av övriga finansiella anläggningstillgångar + (som ska tas upp/dras av)", "id": "8676", "typ": "Numeriskt_B"},
		{"namn": "6.12 Resultat vid avyttring av övriga finansiella anläggningstillgångar - (enligt redovisningen)", "id": "8756", "typ": "Numeriskt_B"},
		{"namn": "6.12 Resultat vid avyttring av övriga finansiella anläggningstillgångar - (som ska tas upp/dras av)", "id": "8776", "typ": "Numeriskt_B"},
		{"namn": "6.13 Övriga finansiella intäkter t.ex. ränteintäkter och utdelningar (enligt redovisningen)", "id": "8657", "typ": "Numeriskt_B"},
		{"namn": "6.13 Övriga finansiella intäkter t.ex. ränteintäkter och utdelningar (som ska tas upp/dras av)", "id": "8677", "typ": "Numeriskt_B"},
		{"namn": "6.14 Nedskrivning av finansiella anläggningstillgångar och kortfristiga placeringar (enligt redovisningen)", "id": "8757", "typ": "Numeriskt_B"},
		{"namn": "6.14 Nedskrivning av finansiella anläggnings- tillgångar och kortfristiga placeringar (som ska tas upp/dras av)", "id": "8777", "typ": "Numeriskt_B"},
		{"namn": "6.15 Räntekostnader och liknande resultatposter (enligt redovisningen)", "id": "8758", "typ": "Numeriskt_A"},
		{"namn": "6.15 Räntekostnader och liknande resultatposter (som ska tas upp/dras av)", "id": "8778", "typ": "Numeriskt_A"},
		{"namn": "6.16 Extraordinära intäkter (enligt redovisningen)", "id": "8658", "typ": "Numeriskt_B"},
		{"namn": "6.16 Extraordinära intäkter (som ska tas upp/dras av)", "id": "8678", "typ": "Numeriskt_B"},
		{"namn": "6.17 Extraordinära kostnader (enligt redovisningen)", "id": "8759", "typ": "Numeriskt_B"},
		{"namn": "6.17 Extraordinära kostnader (som ska tas upp/dras av)", "id": "8779", "typ": "Numeriskt_B"},
		{"namn": "6.18 Återföring av periodiseringsfond + (enligt redovisningen)", "id": "8659", "typ": "Numeriskt_B"},
		{"namn": "6.18 Återföring av periodiseringsfond + (som ska tas upp/dras av)", "id": "8679", "typ": "Numeriskt_B"},
		{"namn": "6.19 Avsättning till periodiseringsfond - (enligt redovisningen)", "id": "8760", "typ": "Numeriskt_B"},
		{"namn": "6.19 Avsättning till periodiseringsfond - (som ska tas upp/dras av)", "id": "8780", "typ": "Numeriskt_B"},
		{"namn": "6.20 Övriga bokslutsdispositioner t.ex. lämnade/mottagna koncernbidrag (enligt redovisningen)", "id": "8660", "typ": "Numeriskt_B"},
		{"namn": "6.20 Övriga bokslutsdispositioner t.ex. lämnade/mottagna koncernbidrag (som ska tas upp/dras av)", "id": "8680", "typ": "Numeriskt_B"},
		{"namn": "6.20 Övriga bokslutsdispositioner t.ex. lämnade/mottagna koncernbidrag (enligt redovisningen)", "id": "8761", "typ": "Numeriskt_B"},
		{"namn": "6.20 Övriga bokslutsdispositioner t.ex. lämnade/mottagna koncernbidrag (som ska tas upp/dras av)", "id": "8781", "typ": "Numeriskt_B"},
		{"namn": "6.21 Skatt på årets resultat... (enligt redovisningen)", "id": "8762", "typ": "Numeriskt_A"},
		{"namn": "6.22 Resultat enligt redovisningen", "id": "8665", "typ": "Numeriskt_A"},
		{"namn": "6.23 Justerat resultat, vinst (som ska tas upp/dras av)", "id": "8685", "typ": "Numeriskt_B"},
		{"namn": "6.23 Justerat resultat, förlust (som ska tas upp/dras av)", "id": "8785", "typ": "Numeriskt_B"}    
	],

	"INK3S-2014": [
		{"namn": "Räkenskapsårets början", "id": "7011", "typ": "Datum_D"},
		{"namn": "Räkenskapsårets slut", "id": "7012", "typ": "Datum_D"},
		{"namn": "7.1 Justerat resultat från föregående sida p.6.23, vinst", "id": "8686", "typ": "Numeriskt_B"},
		{"namn": "7.2 Justerat resultat från föregående sida p.  6.23 , förlust", "id": "8786", "typ": "Numeriskt_B"},
		{"namn": "7.3 Underskott a. Outnyttjat underskott från föregående år", "id": "8787", "typ": "Numeriskt_A"},
		{"namn": "7.3 Underskott b. Reduktion av underskott med hänsyn till exempelvis ackord", "id": "8687", "typ": "Numeriskt_A"},
		{"namn": "7.4 Kostnader som ska dras av men som inte ingår i det redovisade resultatet", "id": "8788", "typ": "Numeriskt_A"},
		{"namn": "7.5a. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet: a. Beräknad schablonintäkt på kvarvarande periodiseringsfonder vid beskattningsårets utgång", "id": "8688", "typ": "Numeriskt_B"},
		{"namn": "b. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet: b. Beräknad schablonintäkt på fondandelar ägda vid ingången av kalenderåret", "id": "8693", "typ": "Numeriskt_A"},
		{"namn": "c. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet: c. Intäkt negativ justerad anskaffningsutgift", "id": "8692", "typ": "Numeriskt_A"},
		{"namn": "d. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet: d. Övriga intäkter", "id": "8689", "typ": "Numeriskt_A"},
		{"namn": "7.6 Skattemässig korrigering av bokfört resultat vid avyttring av fastighet och bostadsrätt: +", "id": "8690", "typ": "Numeriskt_B"},
		{"namn": "7.6 Skattemässig korrigering av bokfört resultat vid avyttring av fastighet och bostadsrätt: -", "id": "8789", "typ": "Numeriskt_B"},
		{"namn": "7.7 Skogs-/substansminskningsavdrag (specificeras på blankett N8)", "id": "8790", "typ": "Numeriskt_A"},
		{"namn": "7.8 Återföringar vid avyttring av fastighet (t.ex. värdeminskningsavdrag, skogsavdrag)", "id": "8691", "typ": "Numeriskt_A"},
		{"namn": "7.9 Överskott (flyttas till huvudblanketten sid 1, p. 1.1)", "id": "8695", "typ": "Numeriskt_B"},
		{"namn": "7.10 Underskott (flyttas till huvudblanketten sid 1, p. 1.2)", "id": "8795", "typ": "Numeriskt_B"},
		{"namn": "7.11 Vid beskattningsårets utgång ej återförda värdeminskningsavdrag avseende byggnader", "id": "8030", "typ": "Numeriskt_B"},
		{"namn": "7.12 Vid beskattningsårets utgång ej återförda värdeminskningsavdrag avseende markanläggningar", "id": "8031", "typ": "Numeriskt_B"},
		{"namn": "7.13 Vid restvärdeavskrivning: återförda belopp för av- och nedskrivning, försäljning, utrangering", "id": "8033", "typ": "Numeriskt_B"},
		{"namn": "7.14 Avdrag för kapitalförvaltningskostnader har gjorts med", "id": "8034", "typ": "Numeriskt_B"},
		{"namn": "Uppdragstagare (t.ex. redovisningskonsult) har biträtt vid upprättandet av årsbokslutet/årsredovisningen: Ja", "id": "8040", "typ": "Str_X"},
		{"namn": "Uppdragstagare (t.ex. redovisningskonsult) har biträtt vid upprättandet av årsbokslutet/årsredovisningen: Nej", "id": "8041", "typ": "Str_X"},
		{"namn": "Årsredovisningen har varit föremål för revision: Ja", "id": "8044", "typ": "Str_X"},
		{"namn": "Årsredovisningen har varit föremål för revision: Nej", "id": "8045", "typ": "Str_X"}
	],

	"INK3SU-2014": [
		{"namn": "Räkenskapsårets början", "id": "7011", "typ": "Datum_D"},
		{"namn": "Räkenskapsårets slut", "id": "7012", "typ": "Datum_D"},
		{"namn": "Stiftelsens ändamål enligt stadgarna - Idrott", "id": "8806", "typ": "Str_X"},
		{"namn": "Stiftelsens ändamål enligt stadgarna - Kultur", "id": "8807", "typ": "Str_X"},
		{"namn": "Stiftelsens ändamål enligt stadgarna - Miljövård", "id": "8808", "typ": "Str_X"},
		{"namn": "Stiftelsens ändamål enligt stadgarna - omsorg om barn och ungdom", "id": "8804", "typ": "Str_X"},
		{"namn": "Stiftelsens ändamål enligt stadgarna - Politisk verksamhet", "id": "8809", "typ": "Str_X"},
		{"namn": "Stiftelsens ändamål enligt stadgarna - Religiös verksamhet", "id": "8810", "typ": "Str_X"},
		{"namn": "Stiftelsens ändamål enligt stadgarna - Sjukvård", "id": "8811", "typ": "Str_X"},
		{"namn": "Stiftelsens ändamål enligt stadgarna - social hjälpverksamhet", "id": "8801", "typ": "Str_X"},
		{"namn": "Stiftelsens ändamål enligt stadgarna - Sveriges försvar och krisberedskap i samverkan med myndighet", "id": "8805", "typ": "Str_X"},
		{"namn": "Stiftelsens ändamål enligt stadgarna - utbildning", "id": "8800", "typ": "Str_X"},
		{"namn": "Stiftelsens ändamål enligt stadgarna - vetenskaplig forskning", "id": "8803", "typ": "Str_X"},
		{"namn": "Stiftelsens ändamål enligt stadgarna - Annan likvärdig verksamhet", "id": "8840", "typ": "Str_36"},
		{"namn": "3.1 Beslutad utdelning av bidrag/ stipendier enligt ändamål", "id": "8850", "typ": "Numeriskt_A"},
		{"namn": "3.2 Bidrag/gåvor", "id": "8857", "typ": "Numeriskt_A"},
		{"namn": "3.3 Kostnader för att erhålla bidrag och gåvor (insamlingskostnader)", "id": "8858", "typ": "Numeriskt_A"},
		{"namn": "3.4 Kapitalavkastning", "id": "8851", "typ": "Numeriskt_A"},
		{"namn": "3.5 Kapitalförvaltningskostnader", "id": "8852", "typ": "Numeriskt_A"},
		{"namn": "3.6 Kostnader för att fullfölja stiftelsens ändamål", "id": "8853", "typ": "Numeriskt_A"},
		{"namn": "3.7 Beslutad utdelning enligt p. 3.1som hör till föregående års kapitalavkastning", "id": "8854", "typ": "Str_X"},
		{"namn": "3.8 Uppgifter för verksamhetsstiftelser - Intäkter", "id": "8855", "typ": "Numeriskt_A"},
		{"namn": "3.9 Uppgifter för verksamhetsstiftelser - Kostnader", "id": "8856", "typ": "Numeriskt_A"},
		{"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Idrott", "id": "8822", "typ": "Str_X"},
		{"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Kultur", "id": "8828", "typ": "Str_X"},
		{"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Miljövård", "id": "8832", "typ": "Str_X"},
		{"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Omsorg om barn och ungdom", "id": "8823", "typ": "Str_X"},
		{"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Politisk verksamhet", "id": "8827", "typ": "Str_X"},
		{"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Religiös verksamhet", "id": "8820", "typ": "Str_X"},
		{"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Sjukvård", "id": "8833", "typ": "Str_X"},
		{"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Social hjälpverksamhet", "id": "8821", "typ": "Str_X"},
		{"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Sveriges försvar och krisberedskap i samverkan med myndighet", "id": "8831", "typ": "Str_X"},
		{"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Utbildning", "id": "8829", "typ": "Str_X"},
		{"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Vetenskaplig forskning", "id": "8830", "typ": "Str_X"},
		{"namn": "Föreningens/trossamfundets ändamål enligt stadgarna - Annan likvärdig verksamhet", "id": "8620", "typ": "Str_36"},
		{"namn": "Föreningar/Trossamfund: Hur stor del av fastigheten används i den egna verksamheten, ange procenttal", "id": "8624", "typ": "Numeriskt_G"},
		{"namn": "Föreningar/Trossamfund: Hur stor del av fastigheten används i den egna verksamheten, ange yta i kvm", "id": "8625", "typ": "Numeriskt_A"},
		{"namn": "4.1 Föreningar/Trossamfund: Intäkter under beskattningsåret: Medlemsavgifter", "id": "8640", "typ": "Numeriskt_A"},
		{"namn": "4.2 Föreningar/Trossamfund: Intäkter under beskattningsåret: Bidrag/gåvor", "id": "8641", "typ": "Numeriskt_A"},
		{"namn": "4.3 Föreningar/Trossamfund:Intäkter under beskattningsåret: Kapitalavkastning (räntor, utdelningar, ej kapitalvinster)", "id": "8642", "typ": "Numeriskt_A"},
		{"namn": "4.4 Föreningar/Trossamfund:Intäkter under beskattningsåret: Kapitalvinster", "id": "8643", "typ": "Numeriskt_A"},
		{"namn": "4.5 Föreningar/Trossamfund: Skattefri rörelse (naturlig anknytning/hävd)", "id": "8629", "typ": "Numeriskt_A"},
		{"namn": "4.6 Föreningar/Trossamfund:Intäkter under beskattningsåret: Skattefri fastighet", "id": "8644", "typ": "Numeriskt_A"},
		{"namn": "4.7 Föreningar/Trossamfund:Intäkter under beskattningsåret: Övriga intäkter", "id": "8645", "typ": "Numeriskt_A"},
		{"namn": "4.8 Föreningar/Trossamfund: Kostnader under beskattningsåret Ändamålsenlig verksamhet/ medlemsverksamhet", "id": "8713", "typ": "Numeriskt_A"},
		{"namn": "4.9 Föreningar/Trossamfund: Kostnader under beskattningsåret: Utdelade bidrag/stipendier enligt ändamålet", "id": "8714", "typ": "Numeriskt_A"},
		{"namn": "4.10 Föreningar/Trossamfund: Kostnader under beskattningsåret: Kapitalförvaltning", "id": "8715", "typ": "Numeriskt_A"},
		{"namn": "4.11 Föreningar/Trossamfund: Kostnader under beskattningsåret: Kapitalförluster", "id": "8716", "typ": "Numeriskt_A"},
		{"namn": "4.12 Föreningar/Trossamfund: Kostnader under beskattningsåret: Skattefri rörelse", "id": "8717", "typ": "Numeriskt_A"},
		{"namn": "4.13 Föreningar/Trossamfund: Kostnader under beskattningsåret: Skattefri fastighet", "id": "8718", "typ": "Numeriskt_A"},
		{"namn": "4.14 Föreningar/Trossamfund: Kostnader under beskattningsåret: Övriga kostnader", "id": "8719", "typ": "Numeriskt_A"}    
	],

    "INK4DU-2014": [
		{"namn": "Bolaget är ett utländskt bolag", "id": "7050", "typ": "Str_X"},
		{"namn": "Räkenskapsårets början", "id": "7011", "typ": "Datum_D"},
		{"namn": "Räkenskapsårets slut", "id": "7012", "typ": "Datum_D"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},

		{"namn": "Person-/organisationsnr", "id": "8100", "typ": "Orgnr_Id"},
        {"namn": "Resultat, summa överskott", "id": "8101", "typ": "Numeriskt_B"},
		{"namn": "Resultat, summa underskott", "id": "8102", "typ": "Numeriskt_B"},
		{"namn": "Delägarens tillskott", "id": "8103", "typ": "Numeriskt_B"},
		{"namn": "Delägarens uttag", "id": "8104", "typ": "Numeriskt_B"},
		{"namn": "Andel avdrag arbetsgivaravgift", "id": "8105", "typ": "Numeriskt_B"},
    ],

	"INK4R-2014": [
		{"namn": "Räkenskapsårets början", "id": "7011", "typ": "Datum_D"},
		{"namn": "Räkenskapsårets slut", "id": "7012", "typ": "Datum_D"},
		{"namn": "2.1 Immateriella anläggningstillgångar, Koncessioner, patent, licenser, varumärken, hyresrätter, goodwill och liknande rättigheter", "id": "7201", "typ": "Numeriskt_A"},
		{"namn": "2.2 Förskott avseende immateriella anläggningstillgångar", "id": "7202", "typ": "Numeriskt_A"},
		{"namn": "2.3 Materiella anläggningstillgångar, byggnader och mark", "id": "7214", "typ": "Numeriskt_A"},
		{"namn": "2.4 Maskiner och inventarier och övriga materiella anläggningstillgångar", "id": "7215", "typ": "Numeriskt_A"},
		{"namn": "2.5 Förbättringsutgifter på annans fastighet", "id": "7216", "typ": "Numeriskt_A"},
		{"namn": "2.6 Pågående nyanläggningar och förskott på materiella anläggningstillgångar", "id": "7217", "typ": "Numeriskt_A"},
		{"namn": "2.7 Finansiella anläggningstillgångar, andelar i koncern- och intresseföretag", "id": "7236", "typ": "Numeriskt_A"},
		{"namn": "2.8 Fordringar hos koncern- och intresseföretag", "id": "7232", "typ": "Numeriskt_A"},
		{"namn": "2.9 Andra finansiella anläggningstillgångar", "id": "7237", "typ": "Numeriskt_A"},
		{"namn": "2.10 Lagertillgångar", "id": "7247", "typ": "Numeriskt_A"},
		{"namn": "2.11 Pågående arbeten för annans räkning", "id": "7245", "typ": "Numeriskt_A"},
		{"namn": "2.12 Förskott till leverantörer", "id": "7246", "typ": "Numeriskt_A"},
		{"namn": "2.13 Kortfristiga fordringar, kundfordringar", "id": "7253", "typ": "Numeriskt_A"},
		{"namn": "2.14 Övriga fordringar", "id": "7264", "typ": "Numeriskt_A"},
		{"namn": "2.15 Förutbetalda kostnader och upplupna intäkter", "id": "7263", "typ": "Numeriskt_A"},
		{"namn": "2.16 Kortfristiga placeringar, övriga kortfristiga placeringar", "id": "7272", "typ": "Numeriskt_A"},
		{"namn": "2.17 Kassa, bank och redovisningsmedel", "id": "7281", "typ": "Numeriskt_A"},
		{"namn": "2.18 Eget kapital, ingående kapital", "id": "7310", "typ": "Numeriskt_A"},
		{"namn": "2.19 Eget kapital, delägarnas nettouttag (-) nettotillskott (+)", "id": "7311", "typ": "Numeriskt_A"},
		{"namn": "2.20 Eget kapital, årets redovisade vinst", "id": "7312", "typ": "Numeriskt_B"},
		{"namn": "2.21 Eget kapital, årets redovisade förlust", "id": "7313", "typ": "Numeriskt_B"},
		{"namn": "2.22 Eget kapital, utgående kapital", "id": "7314", "typ": "Numeriskt_A"},
		{"namn": "2.23 Obeskattade reserver, ackumulerade överavskrivningar", "id": "7322", "typ": "Numeriskt_A"},
		{"namn": "2.24 Övriga obeskattade reserver", "id": "7323", "typ": "Numeriskt_A"},
		{"namn": "2.25 Avsättningar för pensioner och liknande förpliktelser enligt lagen (1967:531) om tryggande av pensionsförpliktelser m.m.", "id": "7331", "typ": "Numeriskt_A"},
		{"namn": "2.26 Övriga avsättningar för pensioner och liknande förpliktelser", "id": "7332", "typ": "Numeriskt_A"},
		{"namn": "2.27 Övriga avsättningar", "id": "7333", "typ": "Numeriskt_A"},
		{"namn": "2.28 Långfristiga skulder, skulder till koncern- och intresseföretag", "id": "7353", "typ": "Numeriskt_A"},
		{"namn": "2.29 Övriga skulder", "id": "7355", "typ": "Numeriskt_A"},
		{"namn": "2.30 Kortfristiga skulder, förskott från kunder", "id": "7362", "typ": "Numeriskt_A"},
		{"namn": "2.31 Pågående arbeten för annans räkning", "id": "7363", "typ": "Numeriskt_A"},
		{"namn": "2.32 Leverantörsskulder", "id": "7365", "typ": "Numeriskt_A"},
		{"namn": "2.33 Skatteskulder", "id": "7368", "typ": "Numeriskt_A"},
		{"namn": "2.34 Övriga skulder", "id": "7371", "typ": "Numeriskt_A"},
		{"namn": "2.35 Upplupna kostnader och förutbetalda intäkter", "id": "7370", "typ": "Numeriskt_A"},
		{"namn": "3.1 Nettomsättning", "id": "7410", "typ": "Numeriskt_A"},
		{"namn": "3.2 Förändring av lager av produkter i arbete, färdiga varor och pågående arbete för annans räkning +", "id": "7411", "typ": "Numeriskt_A"},
		{"namn": "3.2 Förändring av lager av produkter i arbete, färdiga varor och pågående arbete för annans räkning -", "id": "7510", "typ": "Numeriskt_A"},
		{"namn": "3.3 Aktiverat arbete för egen räkning", "id": "7412", "typ": "Numeriskt_A"},
		{"namn": "3.4 Övriga rörelseintäkter", "id": "7413", "typ": "Numeriskt_A"},
		{"namn": "3.5 Råvaror och förnödenheter", "id": "7511", "typ": "Numeriskt_A"},
		{"namn": "3.6 Handelsvaror", "id": "7512", "typ": "Numeriskt_A"},
		{"namn": "3.7 Övriga externa kostnader", "id": "7513", "typ": "Numeriskt_A"},
		{"namn": "3.8 Personalkostnader", "id": "7514", "typ": "Numeriskt_A"},
		{"namn": "3.9 Av- och nedskrivningar av materiella och immateriella anläggningstillgångar", "id": "7515", "typ": "Numeriskt_A"},
		{"namn": "3.10 Övriga rörelsekostnader", "id": "7535", "typ": "Numeriskt_A"},
		{"namn": "3.11 Resultat från andelar i koncernföretag: +", "id": "7414", "typ": "Numeriskt_A"},
		{"namn": "3.11 Resultat från andelar i koncernföretag: -", "id": "7518", "typ": "Numeriskt_A"},
		{"namn": "3.12 Resultat från andelar i intresseföretag: +", "id": "7415", "typ": "Numeriskt_A"},
		{"namn": "3.12 Resultat från andelar i intresseföretag: -", "id": "7519", "typ": "Numeriskt_A"},
		{"namn": "3.13 Resultat från övriga finansiella anläggningstillgångar: +", "id": "7416", "typ": "Numeriskt_A"},
		{"namn": "3.13 Resultat från övriga finansiella anläggningstillgångar: -", "id": "7520", "typ": "Numeriskt_A"},
		{"namn": "3.14 Övriga ränteintäkter och liknande resultatposter", "id": "7417", "typ": "Numeriskt_A"},
		{"namn": "3.15 Nedskrivning av finansiella anläggningstillgångar och kortfristiga placeringar", "id": "7521", "typ": "Numeriskt_A"},
		{"namn": "3.16 Räntekostnader och liknande resultatposter", "id": "7522", "typ": "Numeriskt_A"},
		{"namn": "3.17 Bokslutsdispositioner (t.ex. förändring av överavskrivningar) +", "id": "7427", "typ": "Numeriskt_B"},
		{"namn": "3.17 Bokslutsdispositioner (t.ex. förändring av överavskrivningar) -", "id": "7537", "typ": "Numeriskt_B"},
		{"namn": "3.18 Årets resultat, vinst", "id": "7450", "typ": "Numeriskt_B"},
		{"namn": "3.19 Årets resultat, förlust", "id": "7550", "typ": "Numeriskt_B"}
    ],

    "INK4S-2014": [
		{"namn": "Räkenskapsårets början", "id": "7011", "typ": "Datum_D"},
		{"namn": "Räkenskapsårets slut", "id": "7012", "typ": "Datum_D"},
		{"namn": "4.1 Årets resultat, vinst", "id": "7650", "typ": "Numeriskt_B"},
		{"namn": "4.2 Årets resultat, förlust", "id": "7750", "typ": "Numeriskt_B"},
		{"namn": "4.3a. Nedskrivning av finansiella tillgångar", "id": "7652", "typ": "Numeriskt_A"},
		{"namn": "b. Andra bokförda kostnader", "id": "7653", "typ": "Numeriskt_A"},
		{"namn": "4.4a. Skogs-/substansminskningsavdrag", "id": "7761", "typ": "Numeriskt_B"},
		{"namn": "b. Andra ej bokförda kostnader", "id": "7764", "typ": "Numeriskt_A"},
		{"namn": "4.5a. Bokförda intäkter som inte ska tas upp: Ackordsvinster", "id": "7752", "typ": "Numeriskt_A"},
		{"namn": "b. Andra bokförda intäkter", "id": "7754", "typ": "Numeriskt_A"},
		{"namn": "4.6a. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet a. Återföringar av värdeminskningsavdrag m.m. vid avyttring av fastighet (skogs- och substansminskningsavdrag specificera på N8)", "id": "7662", "typ": "Numeriskt_A"},
		{"namn": "b. Beräknad schablonintäkt på fondandelar ägda vid ingången av kalenderåret", "id": "7668", "typ": "Numeriskt_A"},
		{"namn": "c. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet b. Andra ej bokförda intäkter", "id": "7665", "typ": "Numeriskt_A"},
		{"namn": "4.7 Delägarnas förmåner och andra uttagna varor och tjänster: Bokförd intäkt av gjorda uttag", "id": "7766", "typ": "Numeriskt_A"},
		{"namn": "4.8a. Resultat från andel i handelsbolag: Bokförd intäkt/vinst", "id": "7741", "typ": "Numeriskt_A"},
		{"namn": "b. Skattemässigt överskott enligt blankett N3B", "id": "7642", "typ": "Numeriskt_B"},
		{"namn": "c. Resultat från andel i handelsbolag: Bokförd kostnad/förlust", "id": "7641", "typ": "Numeriskt_B"},
		{"namn": "d. Skattemässigt underskott enligt blankett N3B", "id": "7742", "typ": "Numeriskt_A"},
		{"namn": "4.9 Skattemässig justering av bokfört resultat för avskrivningar på byggnader/fast egendom samt vid restvärdesavskrivning på maskiner och inventarier (+)", "id": "7666", "typ": "Numeriskt_B"},
		{"namn": "4.9 Skattemässig justering av bokfört resultat för avskrivningar på byggnader/fast egendom samt vid restvärdesavskrivning på maskiner och inventarier (-)", "id": "7765", "typ": "Numeriskt_B"},
		{"namn": "4.10a. Bokfört resultat avyttrad fastighet/bostadsrätt: Bokförd vinst", "id": "7767", "typ": "Numeriskt_A"},
		{"namn": "b. Bokfört resultat avyttrad fastighet/bostadsrätt: Bokförd förlust", "id": "7669", "typ": "Numeriskt_A"},
		{"namn": "4.11a. Bokför resultat avyttrade värdepapper och handelsbolagsandelar: Bokförd vinst", "id": "7768", "typ": "Numeriskt_A"},
		{"namn": "b. Bokför resultat avyttrade värdepapper och handelsbolagsandelar: Bokförd förlust", "id": "7643", "typ": "Numeriskt_A"},
		{"namn": "4.12 Överskott", "id": "7670", "typ": "Numeriskt_B"},
		{"namn": "4.13 Underskott", "id": "7770", "typ": "Numeriskt_B"},
		{"namn": "4.14 Årets begärda och tidigare års medgivna värdeminskningsavdrag på byggnader som finns kvar vid beskattningsårets utgång", "id": "8020", "typ": "Numeriskt_A"},
		{"namn": "4.15 Årets begärda och tidigare års medgivna värdeminskningsavdrag på markanläggningar som finns kvar vid beskattningsårets utgång", "id": "8021", "typ": "Numeriskt_A"},
		{"namn": "Uppdragstagare (t.ex. redovisningskonsult) har biträtt vid upprättandet av årsbokslutet/årsredovisningen - Ja", "id": "8040", "typ": "Str_X"},
		{"namn": "Uppdragstagare (t.ex. redovisningskonsult) har biträtt vid upprättandet av årsbokslutet/årsredovisningen - Nej", "id": "8041", "typ": "Str_X"},
		{"namn": "Årsredovisningen har varit föremål för revision - Ja", "id": "8044", "typ": "Str_X"},
		{"namn": "Årsredovisningen har varit föremål för revision - Nej", "id": "8045", "typ": "Str_X"}
    ]
};
